/**
 * Compose a side-by-side parity sheet: for each screen, the design mock next to the app render, so a
 * reviewer approves the PICTURE, not the prose (CLAUDE.md → "Pixel parity"). Two outputs:
 *   - <out>.html — self-contained (images inlined as data URIs), openable anywhere, attachable to a PR;
 *   - <out>.png  — a full-page screenshot of that HTML, for chat / quick glance.
 *
 * The app column degrades honestly: when a screen has no app render yet it shows a labelled
 * placeholder, never a blank that reads as "matches".
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import { launch, contextDefaults } from "./browser.mjs";

const STATUS = {
  "": { chip: "", color: "#5b6b73" },
  todo: { chip: "⬜ not started", color: "#5b6b73" },
  wip: { chip: "🔧 in progress", color: "#b8860b" },
  review: { chip: "👁 awaiting visual OK", color: "#2563eb" },
  signed: { chip: "✅ signed off", color: "#127a3d" },
};

async function dataUri(path) {
  if (!path) return null;
  const buf = await readFile(path).catch(() => null);
  if (!buf) return null;
  return `data:image/png;base64,${buf.toString("base64")}`;
}

function esc(s) {
  return String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
}

/**
 * @param {object} o
 * @param {string} o.title
 * @param {Array<{label:string, sub?:string, status?:string, mock?:string, app?:string,
 *                mockNote?:string, appNote?:string, logicalW?:number}>} o.rows
 * @param {string} o.out  base path (writes o.out + ".html" and ".png")
 * @param {import('playwright-core').Browser} [o.browser]  reuse a browser if you have one
 */
export async function buildSheet(o) {
  const rowsHtml = [];
  for (const r of o.rows) {
    const mock = await dataUri(r.mock);
    const app = await dataUri(r.app);
    const w = r.logicalW || 360;
    const st = STATUS[r.status || ""] || STATUS[""];
    rowsHtml.push(`
      <section class="row">
        <header>
          <div class="label">${esc(r.label)}${r.sub ? `<span class="sub">${esc(r.sub)}</span>` : ""}</div>
          ${st.chip ? `<span class="status" style="--c:${st.color}">${esc(st.chip)}</span>` : ""}
        </header>
        <div class="pair">
          <figure>
            ${mock ? `<img width="${w}" src="${mock}" alt="mock">` : `<div class="missing">mock render missing</div>`}
            <figcaption>DESIGN MOCK${r.mockNote ? ` · ${esc(r.mockNote)}` : ""}</figcaption>
          </figure>
          <figure>
            ${app ? `<img width="${w}" src="${app}" alt="app">` : `<div class="missing pending">app render — ${esc(r.appNote || "wire per-screen fixture")}</div>`}
            <figcaption>APP${r.appNote && app ? ` · ${esc(r.appNote)}` : ""}</figcaption>
          </figure>
        </div>
      </section>`);
  }

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(o.title)}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { margin: 0; background: #eef1f3; color: #14181b;
         font: 14px/1.5 -apple-system, "Segoe UI", Roboto, Inter, sans-serif; padding: 28px; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  .meta { color: #5b6b73; margin: 0 0 24px; font-size: 12.5px; }
  .row { background: #fff; border: 1px solid #dfe4e7; border-radius: 14px; padding: 18px 20px 22px;
         margin: 0 0 20px; box-shadow: 0 1px 3px rgba(20,24,27,.05); }
  .row header { display: flex; align-items: center; justify-content: space-between; margin: 0 0 14px; gap: 12px; }
  .label { font-weight: 700; font-size: 15px; }
  .label .sub { color: #5b6b73; font-weight: 500; margin-left: 8px; font-size: 12.5px; }
  .status { color: var(--c); border: 1px solid var(--c); border-radius: 999px; padding: 2px 10px;
            font-size: 11.5px; font-weight: 700; white-space: nowrap; }
  .pair { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; align-items: start; }
  figure { margin: 0; }
  figure img { width: 100%; max-width: 100%; height: auto; display: block; border: 1px solid #e4e8ea;
               border-radius: 12px; background: #fff; }
  figcaption { color: #5b6b73; font-size: 11px; font-weight: 700; letter-spacing: .04em; margin-top: 8px; }
  .missing { display: grid; place-items: center; min-height: 320px; border: 2px dashed #c6ccd0;
             border-radius: 12px; color: #8a969c; font-weight: 600; text-align: center; padding: 20px; }
  .missing.pending { border-color: #f0c674; color: #b8860b; background: #fffaf0; }
</style></head>
<body>
  <h1>${esc(o.title)}</h1>
  <p class="meta">Design mock (source of truth) vs app render · one browser, one viewport per side · generated by tools/parity</p>
  ${rowsHtml.join("\n")}
</body></html>`;

  await mkdir(dirname(o.out), { recursive: true });
  const htmlPath = o.out + ".html";
  const pngPath = o.out + ".png";
  await writeFile(htmlPath, html);

  const browser = o.browser || (await launch());
  try {
    const ctx = await browser.newContext(contextDefaults({ viewport: { width: 900, height: 1200 }, deviceScaleFactor: 1 }));
    const page = await ctx.newPage();
    await page.setContent(html, { waitUntil: "load" });
    await page.evaluate(() => (document.fonts ? document.fonts.ready : null));
    await writeFile(pngPath, await page.screenshot({ fullPage: true, type: "png" }));
    await ctx.close();
  } finally {
    if (!o.browser) await browser.close();
  }
  return { htmlPath, pngPath };
}
