(function(){
const {I,cell,sec,hero,disc,t,s,ft,cta,gh,lk,top,steps,kyc,locDialog,notifDialog,ntf,homeHd,tiles}=K;
const ex=`<span class="ex">${I('x','m')}</span>`;
const b=x=>`<div class="body">${x}</div>`;
const sheet=x=>`<div class="dim"></div><div class="sheet"><div class="grab"></div>${x}</div>`;
const sbtn=(...x)=>`<div style="display:flex;flex-direction:column;gap:4px;margin-top:20px">${x.join('')}</div>`;
const home=(x='')=>homeHd(1)+tiles()+x;
// customer
const pc1=()=>home(sheet(hero('',disc('nav'),150)+t(PC.locA,PC.locB)+s(PC.locBody)+sbtn(cta(PC.locCta,'nav'),lk(PC.locAlt))));
const order=()=>`<div class="pill" style="background:#E9F8EF;color:#006630">${I('check','s')}${PC.placed}</div>`;
const pc8=()=>b(order()+`<div style="margin-top:16px"></div>`+hero('',ntf('bike',PC.ex1T,PC.ex1B,'transform:scale(.94)')+ntf('lock',PC.ex2T,PC.ex2B)+ntf('check',PC.ex3T,PC.ex3B,'transform:scale(.94)'),250)+t(PC.notifA,PC.notifB)+s(PC.notifBody))+ft(cta(PC.notifCta,'bell'),lk(PC.notifAlt));
const p1=()=>b(hero('v',disc('pin'))+t(RP.locA,RP.locB,'vi')+`<div class="pts"><div class="pt"><b>${I('pin','s')}</b>${RP.loc1}</div><div class="pt"><b>${I('user','s')}</b>${RP.loc2}</div><div class="pt"><b>${I('power','s')}</b>${RP.loc3}</div></div>`)+ft(cta(RP.locCta),lk(RP.notNow));
const p3=()=>b(hero('v',`<div style="font-size:12px;font-weight:600;color:#4B2FBF;letter-spacing:.06em;text-transform:uppercase">${RP.tripTag}</div>`+ntf('nav',RP.fgsTitle,RP.fgsBody,'width:288px;align-items:flex-start'))+t(RP.tripA,RP.tripB,'vi')+s(RP.tripBody))+ft(cta(RP.tripCta));
const p9=()=>b(hero('v',`<div style="width:276px;background:#fff;border-radius:20px;padding:16px;box-shadow:0 0 0 1px rgba(20,24,27,.06)"><div style="display:flex;justify-content:space-between;align-items:center"><span class="pill" style="background:#FFD23F;color:#3D3100;min-height:26px">${RP.offerTag}</span><span style="font-size:13px;font-weight:600;color:#5B6670">0:58</span></div><div style="font-size:22px;font-weight:700;margin-top:10px">${RP.offerFare}</div><div style="font-size:13px;color:#5B6670;margin-top:2px">${RP.offerRoute}</div><div style="height:4px;border-radius:2px;background:#ECE8FF;margin-top:12px"><div style="width:92%;height:4px;border-radius:2px;background:#4B2FBF"></div></div></div>`)+t(RP.notifA,RP.notifB,'vi')+s(RP.notifBody)+`<button class="pill b" style="margin-top:16px;background:#fff;border:1px solid #E2E6EA">${I('vol','s')}${RP.testPing}</button>`)+ft(cta(RP.notifCta,'bell'),lk(RP.notNow));
const u1=(body=UP.body,c=cta(UP.cta),l=lk(UP.help,'chat'),extra=`<div class="pill" style="margin-top:16px;background:#F6F7F8;font-weight:400"><b style="color:#006630">${UP.whatsNew}</b>Faster live tracking</div>`)=>b(hero('g',`<img src="assets/brand/lyniago-mark-mono.svg" alt="" style="width:88px;height:88px;filter:brightness(0) invert(1)">`,280)+t(UP.title,UP.titleB)+s(body)+extra)+ft(c,l);
const f4=(tone,ic,a,bb,body,chips)=>b(hero(tone,disc(ic))+t(a,bb,tone==='r'?'rd':'')+(body?s(body):'')+(chips?`<div class="chips">${chips.map(([i,x])=>`<span class="pill">${I(i,'s')}${x}</span>`).join('')}</div>`:'')+`<div class="box n" style="justify-content:space-between;margin-top:20px"><span style="color:#5B6670">${KY.triesLeft}</span><span class="tries"><i></i><i class="u"></i></span></div>`)+ft(cta(KY.tryAgain,'cam'),lk(KY.help,'chat'));
const d2=(idField,help,c=cta(PD.save))=>top()+`<div class="big">${PD.title}</div>`+b(`<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><div><div class="flab">${PD.first}</div><div class="fld">Chipo</div></div><div><div class="flab">${PD.last}</div><div class="fld">Marufu</div></div></div><div class="fld" style="margin-top:12px;background:#F6F7F8;border:0;gap:10px"><span style="color:#00B14F;display:flex">${I('shield','m')}</span><span style="flex:1">+263 77 245 1180</span><span style="font-size:14px;font-weight:600;color:#006630">${PD.phoneVerified}</span></div><div class="flab" style="margin-top:24px">${PD.idLabel} <span style="font-weight:400">· ${PD.idOpt}</span></div>${idField}${help}`)+ft(c);
const idPh=`<div class="fld" style="color:#AEB6BD">${PD.idPh}</div>`,idWhy=`<div class="fhelp">${PD.idWhy}</div>`;
const bdRows=(photo,plate)=>`<div class="list"><div class="li"><span class="dd ok">${I('id','m')}</span><span class="n">${BD.id}</span><span class="v ok">${BD.verified}</span></div>${photo}${plate}</div>`;
const addBtn=`<button class="pill" style="min-height:var(--target-min,44px);background:#E9F8EF;color:#006630">${I('plus','s')}${BD.add}</button>`;
const rPhoto=(r=addBtn,ic=`<span class="dd">${I('user','m')}</span>`,sub=BD.photoSub)=>`<div class="li">${ic}<span class="n">${BD.photo}<small>${sub}</small></span>${r}</div>`;
const rPlate=(r=addBtn,name=BD.plate,sub=BD.plateSub)=>`<div class="li"><span class="dd">${I('bike','m')}</span><span class="n">${name}<small>${sub}</small></span>${r}</div>`;
const prog=n=>`<div style="display:flex;align-items:center;gap:12px;margin-bottom:16px"><div style="flex:1;display:flex;gap:4px">${[1,2,3].map(i=>`<i style="flex:1;height:6px;border-radius:3px;background:${i<=n?'#00B14F':'#E2E6EA'}"></i>`).join('')}</div><span style="font-size:14px;font-weight:600;color:#5B6670">${n} ${BD.progress}</span></div>`;
const e1=(rows=bdRows(rPhoto(),rPlate()),n=1)=>top()+`<div class="big">${BD.title}</div>`+b(prog(n)+rows+`<div class="fhelp" style="margin:12px 4px 0">${BD.optional}</div>`);
const toast=x=>`<div class="toast">${I('check','m')}${x}</div>`;
const greetHd=st=>`<div style="background:#E9F8EF;padding:36px 16px 16px;display:flex;align-items:center;gap:12px;flex:none"><div style="flex:1;min-width:0"><div style="font-size:20px;font-weight:700;letter-spacing:-.02em;white-space:nowrap">Good morning, Tendai</div><div style="display:flex;gap:6px;align-items:center;font-size:13px;margin-top:4px;white-space:nowrap;overflow:hidden">${st}</div></div><span style="width:28px;height:28px;border-radius:50%;background:#FFD23F;box-shadow:0 0 0 5px rgba(255,210,63,.35);flex:none"></span><span style="width:44px;height:44px;border-radius:50%;background:#fff;display:grid;place-items:center;color:#006630;flex:none">${I('bell','m')}</span></div>`;
const rboard=x=>greetHd(`<span class="stp a" style="width:12px;height:12px;border-width:2px;border-color:#E2E6EA;border-top-color:#5B6670"></span><b style="font-weight:600">Reconnecting…</b><span style="color:#5B6670">·</span><span style="color:#006630;font-weight:600;display:flex;gap:3px;align-items:center">${I('pin','s')}12 Samora …</span>`)+b(x);
const job=(f,r)=>`<div class="job"><b>${f}</b><div>${r}</div></div>`;
const splash=(w,h,{nav,offline,rider=1}={})=>{const bot=nav==='3'?64:nav==='g'?36:24;const cardH=offline?76:116;const wmTop=Math.round((h-bot-cardH)/2)-40;
const card=offline?`<div class="li"><span class="dd">${I('wifioff','m')}</span><span class="n">${SP.offline}<small>${SP.offlineBody}</small></span></div>`:`<div class="li"><span class="stp d">${I('check','s')}</span><span class="n">${SP.r1}</span></div><div class="li" style="border-top:1px solid #E2E6EA"><span class="stp a"></span><span class="n">${SP.r2}</span></div>`;
return `<div class="sp" style="position:absolute;inset:0"><div class="orb"></div><div class="sun"></div><div class="wm" style="top:${wmTop}px">LyniaGo</div><div class="spc" style="bottom:${bot}px">${card}</div>${nav==='3'?'<div class="navb"><i></i><i></i><i></i></div>':nav==='g'?'<div class="gest"><i></i></div>':''}</div>`};
const kb=`<div class="kb">${[10,9,9,5].map(n=>`<div>${'<span></span>'.repeat(n)}</div>`).join('')}</div>`;
const sm={w:320,h:640,c:'sm'},fs={c:'fs13'};

const H=[];const add=(...a)=>H.push(cell(...a));
H.push(`<div class="intro"><h1>First run v2 · every state</h1><p>Android dialogs, edge cases, 320×640, font scale 1.3. Copy lives in <b>fr-copy.js</b>.</p></div>`);

H.push(sec('A · Customer location','Asked when Home needs an address. Sheet over Home, like H5'));
add('PC1','Explainer',pc1());
add('PC2','Android dialog',pc1()+locDialog('p'));
add('PC3','Approximate chosen',home(sheet(hero('',disc('pin'),130)+t(PC.approxA,PC.approxB)+s(PC.approxBody)+sbtn(cta(PC.approxCta,'nav'),lk(PC.approxAlt)))));
add('PC4','Denied once → type it',home(sheet(`<div class="t" style="margin-top:0">${PC.deniedA} <em>${PC.deniedB}</em></div>`+s(PC.deniedBody)+`<div class="fld on" style="margin-top:16px;gap:8px">${I('search','m')}Samora<span class="caret"></span></div><div class="list" style="margin-top:12px"><div class="li"><span class="dd">${I('pin','m')}</span><span class="n">Samora Machel Ave<small>CBD, Harare</small></span></div><div class="li"><span class="dd">${I('pin','m')}</span><span class="n">Samora Machel Ave East<small>Eastlea, Harare</small></span></div></div>`)));
add('PC5','Denied for good',home(sheet(t(PC.foreverA,PC.foreverB,'rd').replace('margin-top:24px','')+s(PC.foreverBody)+steps(PC.step1,PC.step2,PC.step3)+sbtn(cta(PC.openSettings),lk(PC.locAlt)))));
add('PC6','Phone GPS off',home(sheet(hero('n',disc('pin'),130)+t(PC.gpsA,PC.gpsB)+s(PC.gpsBody)+sbtn(cta(PC.gpsCta),lk(PC.locAlt)))));
add('PC7','Granted → H1',homeHd(0)+tiles()+`<div style="padding:0 16px"><div style="font-size:18px;font-weight:700;margin-top:8px">Popular near you</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px"><div style="height:120px;border-radius:16px;background:#FFE0D6"></div><div style="height:120px;border-radius:16px;background:#E4DEFF"></div></div></div>`+toast(PC.grantedToast));

H.push(sec('A · Customer notifications','Asked right after the first order is placed'));
add('PC8','Explainer',pc8());
add('PC9','Android dialog',pc8()+notifDialog());
add('PC10','Declined',b(order()+`<div style="margin-top:16px"></div>`+hero('n',disc('belloff'),200)+t(PC.offA,PC.offB)+s(PC.offBody))+ft(cta(PC.offCta)));
add('PC11','Settings · off',top()+`<div class="big">Settings</div>`+b(`<div class="box bad" style="align-items:flex-start;border-radius:20px;padding:16px;margin-top:4px"><span class="dd" style="background:#fff;color:#8F2418">${I('bell','m')}</span><div><div style="font-weight:700">${PC.setOffTitle}</div><div style="color:#14181B;margin-top:2px">${PC.setOffBody}</div><button class="pill b" style="margin-top:12px;background:#fff;color:#8F2418">${PC.setOffCta}</button></div></div><div class="list" style="margin-top:16px"><div class="li"><span class="dd ok">${I('user','m')}</span><span class="n">${PD.row}<small>${PD.rowSub}</small></span>${I('chev','m ch')}</div><div class="li"><span class="dd">${I('bell','m')}</span><span class="n">Order updates</span><span class="tg off"></span></div></div>`));

H.push(sec('B · Rider permissions','Once per install, after sign-in, before the first board'));
add('P1','Location',p1());
add('P2','Android dialog',p1()+locDialog('p'));
add('P3','During a job',p3());
add('P4','Approximate chosen',b(hero('v',disc('pin'))+t(RP.approxA,RP.approxB,'vi')+s(RP.approxBody))+ft(cta(RP.approxCta,'nav'),lk(RP.notNow)));
add('P5','Denied once',b(hero('r',disc('pin'))+t(RP.deniedA,RP.deniedB,'rd')+s(RP.deniedBody))+ft(cta(RP.askAgain),lk(RP.continue)));
add('P6','Denied for good',b(hero('r',disc('pin'),180)+t(RP.deniedA,RP.deniedB,'rd')+s(RP.foreverBody)+steps(RP.step1,RP.step2,RP.step3))+ft(cta(RP.openSettings),lk(RP.turnedOn)));
add('P7','Phone GPS off',b(hero('n',disc('pin'))+t(RP.gpsA,RP.gpsB)+s(RP.gpsBody))+ft(cta(PC.gpsCta),lk(RP.notNow)));
add('P8','Granted · toast on P3',p3()+toast(RP.grantedToast));
add('P9','Notifications',p9());
add('P10','Android dialog',p9()+notifDialog());
add('P11','Blocked',b(hero('r',disc('belloff'),180)+t(RP.blockedA,RP.blockedB,'rd')+s(RP.blockedBody)+steps(RP.step1,RP.nStep2,RP.nStep3))+ft(cta(RP.openSettings),lk(RP.turnedOn)));
add('P12','Job alarm muted',b(hero('r',disc('mute'),180)+t(RP.mutedA,RP.mutedB,'rd')+s(RP.mutedBody)+steps(RP.step1,RP.mStep2,RP.mStep3))+ft(cta(RP.openSettings),lk(RP.testPing,'vol')));
add('P13','All set',b(hero('',`<img src="assets/illustrations/trust-verified.svg" alt="" style="height:140px">`)+t(RP.doneA,RP.doneB)+s(RP.doneBody))+ft(cta(RP.goOnline,'power')));
add('P14','Skipped → board',rboard(`<div class="box bad" style="margin-top:0">${I('belloff','m')}<span style="flex:1">${RP.j8}</span><b>${RP.turnOn}</b></div><div style="margin-top:120px;text-align:center"><span class="mk">${I('pin')}</span><div style="font-size:18px;font-weight:600;margin-top:24px">${RP.g8A}</div><div class="s" style="margin-top:4px">${RP.g8Body}</div><button class="pill b" style="margin:20px auto 0">${RP.turnOn}</button></div>`));
add('P15','Settings · location off',top()+`<div class="big">Settings</div>`+b(`<div class="list" style="margin-top:8px"><div class="li"><span class="dd">${I('vol','m')}</span><span class="n">Job alerts<small>Ping and food-offer alarm</small></span><span class="tg"></span></div><div class="li" style="background:#FAEDEB"><span class="dd bad" style="background:#fff">${I('pin','m')}</span><span class="n" style="color:#8F2418">Location<small style="color:#8F2418">Off · You can’t receive jobs</small></span><span class="tg off"></span></div><div class="li"><span class="dd">${I('bat','m')}</span><span class="n">Battery saver<small>Keep trips running</small></span>${I('chev','m ch')}</div></div><div class="fhelp" style="margin:12px 4px">Tap Location to reopen P1.</div>`));
add('P16','Battery (optional)',b(hero('v',disc('bat'))+t(RP.batA,RP.batB,'vi')+s(RP.batBody))+ft(cta(RP.batCta),lk(RP.notNow)));

H.push(sec('C · App update','White screen, green mark panel: white text on #00B14F fails AA'));
add('U1','Required',u1());
add('U2','No store link',u1(UP.noLinkBody,cta(UP.noLinkCta,'chat'),'',''));
add('U3','Offline',u1(UP.body,`<button class="cta" style="background:#E2E6EA;color:#5B6670">${UP.cta}</button>`,lk(UP.help,'chat'),`<div class="box n">${I('wifioff','m')}${UP.offlineNote}</div>`));
add('U4a','Soft · Home',homeHd(0)+`<div style="margin:12px 16px 0;border-radius:20px;background:#063B22;color:#fff;padding:14px 14px 14px 16px;display:flex;gap:12px;align-items:center;position:relative"><span style="position:absolute;right:12px;top:-10px;font-size:11px;font-weight:700;color:#8F2418;background:#FAEDEB;padding:2px 6px;border-radius:4px">NEEDS BACKEND</span><div style="flex:1"><div style="font-weight:700">${UP.softTitle}</div><div style="font-size:13px;color:#B9E8CC;margin-top:2px">${UP.softBody}</div></div><button class="pill b" style="background:#00B14F;color:#fff">${UP.softCta}</button><span style="width:44px;height:44px;display:grid;place-items:center;color:#B9E8CC">${I('x','m')}</span></div>`+tiles()+``);
add('U4b','Soft · rider board',rboard(`<div style="border-radius:20px;background:#4B2FBF;color:#fff;padding:14px 14px 14px 16px;display:flex;gap:12px;align-items:center"><div style="flex:1"><div style="font-weight:700">${UP.softTitle}</div><div style="font-size:13px;color:#DCD5FF;margin-top:2px">${UP.softBody}</div></div><button class="pill b" style="background:#fff;color:#4B2FBF">${UP.softCta}</button></div>`+job('$3.50 · 2.4 km','Avondale → Belgravia')+job('$5.00 · 4.1 km','Sadza Republic → Mt Pleasant')));

H.push(sec('D · Personal details','Settings → Personal details. Inline “Saved” on the button: stays where your eyes are'));
add('D2','Edit',d2(idPh,idWhy));
add('D3','Saved',d2(`<div class="fld">63-482913K07</div>`,idWhy,`<button class="cta" style="background:#E9F8EF;color:#006630">${I('check','m')}${PD.saved}</button>`));
add('D4','ID on another account',d2(`<div class="fld err">63-482913K07</div>`,`<div class="box bad" style="align-items:flex-start">${I('alert','m')}<div><b>${PD.takenA} ${PD.takenB}</b><div style="color:#14181B;margin-top:2px">${PD.takenBody}</div></div></div>`,cta(PD.takenCta,'chat')));
add('D5','Invalid format',d2(`<div class="fld err">63 4829<span class="caret" style="background:#C0392B"></span></div>`,`<div class="fhelp err">${I('alert','s')}${PD.invalid}</div>`));
add('D6','Verified rider',d2(`<div class="fld" style="background:#F6F7F8;border:0;gap:10px"><span style="flex:1;letter-spacing:.08em">••-••••••K07</span><span style="font-size:14px;font-weight:600;color:#006630;display:flex;gap:4px;align-items:center">${I('check','s')}${BD.verified}</span></div>`,`<div class="fhelp">${PD.idVerified}</div>`));
add('D7','320 · keyboard up',top()+`<div class="big" style="font-size:24px">${PD.title}</div><div class="body" style="padding-top:12px"><div class="flab">${PD.idLabel} · ${PD.idOpt}</div><div class="fld on">63-4829<span class="caret"></span></div>${idWhy}</div>`+ft(cta(PD.save))+kb,sm);

H.push(sec('E · Bike & documents','Photo and plate are optional. Plate saves instantly, shows “Checking” until ops confirm'));
add('E1','New rider',e1());
add('E2a','Add photo · choose',e1()+sheet(`<div style="font-size:20px;font-weight:700;margin-bottom:12px">${BD.photoSheet}</div><div class="list"><div class="li"><span class="dd ok">${I('cam','m')}</span><span class="n">${BD.camera}</span></div><div class="li"><span class="dd ok">${I('img','m')}</span><span class="n">${BD.gallery}</span></div></div>`));
add('E2b','Capture guide',`<div style="position:absolute;inset:0;background:#14181B;color:#fff;display:flex;flex-direction:column;align-items:center"><div style="align-self:stretch;height:56px;margin-top:24px;display:flex;align-items:center;padding:0 8px"><span style="width:44px;height:44px;display:grid;place-items:center">${I('x')}</span></div><div style="font-size:26px;font-weight:700;margin-top:8px">${BD.guideA} <span style="color:#00B14F">${BD.guideB}</span></div><div style="width:220px;height:290px;border-radius:50%;border:3px dashed rgba(255,255,255,.7);margin-top:28px"></div><div class="chips" style="justify-content:center;margin-top:24px">${[['sun',BD.guide3],['user',BD.guide2],['img',BD.guide1]].map(([i,x])=>`<span class="pill" style="background:rgba(255,255,255,.12);color:#fff">${I(i,'s')}${x}</span>`).join('')}</div><div style="margin-top:auto;margin-bottom:28px;width:76px;height:76px;border-radius:50%;border:4px solid #fff;display:grid;place-items:center"><span style="width:58px;height:58px;border-radius:50%;background:#fff"></span></div></div>`,{c:'dark'});
add('E2c','Preview',b(`<div style="width:240px;height:240px;border-radius:50%;margin:24px auto 0;background:repeating-linear-gradient(135deg,#E9F8EF 0 10px,#DDF2E5 10px 20px);display:grid;place-items:center;font:12px ui-monospace,monospace;color:#5B6670">rider photo</div>`+`<div class="t" style="text-align:center">Looking <em>good</em></div>`)+ft(cta(BD.use),lk(BD.retake,'refresh')));
add('E2d','Uploading',e1(bdRows(rPhoto(`<span class="v">${BD.uploading}</span>`,`<span style="width:36px;height:36px;border-radius:50%;background:repeating-linear-gradient(135deg,#E9F8EF 0 4px,#DDF2E5 4px 8px);flex:none"></span>`,`<span style="display:block;height:4px;border-radius:2px;background:#E2E6EA;margin-top:6px"><span style="display:block;width:60%;height:4px;border-radius:2px;background:#00B14F"></span></span>`),rPlate())));
add('E4a','Plate sheet',e1()+sheet(`<div style="font-size:20px;font-weight:700;margin-bottom:12px">${BD.plateTitle}</div><div class="fld on" style="font-weight:600;letter-spacing:.06em">ABZ 4417<span class="caret"></span></div><div class="fhelp">${BD.plateSub}</div>`+sbtn(cta(BD.plateSave))));
add('E4b','Plate error',e1()+sheet(`<div style="font-size:20px;font-weight:700;margin-bottom:12px">${BD.plateTitle}</div><div class="fld err" style="font-weight:600;letter-spacing:.06em">AB 44<span class="caret" style="background:#C0392B"></span></div><div class="fhelp err">${I('alert','s')}${BD.plateErr}</div>`+sbtn(cta(BD.plateSave))));
add('E4c','Plate saved · checking',e1(bdRows(rPhoto(),rPlate(`<span class="pill" style="background:#FFF6D6;color:#3D3100">${I('clock','s')}${BD.inReview}</span>`,'ABZ 4417',BD.plateReview)),2));
add('E5','All set',top()+b(hero('',`<span class="disc" style="background:#00B14F;color:#fff">${I('check','l')}</span>`,200).replace('style="height:200px"','style="height:200px;margin-top:-28px"')+t(BD.doneA,BD.doneB)+`<div style="margin-top:20px">${bdRows(rPhoto(`<span class="v">${BD.change}</span>`,`<span class="dd ok" style="font-weight:700;font-size:13px">TM</span>`,BD.verified),rPlate(`<span class="v">${BD.edit}</span>`,'ABZ 4417',BD.verified))}</div>`));
add('E6','Upload failed',b(hero('r',disc('upload'))+t(BD.failA,BD.failB,'rd')+s(BD.failBody))+ft(cta(BD.retry,'refresh')));

H.push(sec('F · ID-check outcomes','One shell: hero, bold line, steps, one action. Never names the vendor'));
add('F8','Just finished',ex+b(hero('',`<span class="disc"><span class="stp a" style="width:48px;height:48px;border-width:5px"></span></span>`)+t(KY.justA,KY.justB)+s(KY.justBody)+kyc('a','…')));
add('F1','In review · our team',ex+b(hero('',disc('clock'))+t(KY.reviewA,KY.reviewB)+s(KY.reviewBody)+kyc('a','In review')));
add('F3','Unfinished',ex+b(hero('',disc('id'))+t(KY.unfA,'Tendai')+s(KY.unfBody)+kyc('n','~2 min'))+ft(cta(KY.unfCta,'arrow')));
add('F5','Locked',ex+b(hero('',disc('chat'))+t(KY.lockedA,KY.lockedB)+s(KY.lockedBody))+ft(cta(KY.msg,'chat')));
add('F6','ID expired',ex+b(hero('r',disc('id'))+t(KY.expA,KY.expB,'rd')+s(KY.expBody))+ft(cta(KY.expCta,'cam')));
add('F2','Held for review',ex+b(hero('',disc('shield'))+t(KY.heldA,KY.heldB)+s(KY.heldBody)+kyc('a','In review'))+ft(lk(KY.help,'chat')));
add('F4a','Declined · blurry',ex+f4('r','cam',KY.blurryA,KY.blurryB,'',[['sun',KY.blurryTip1],['id',KY.blurryTip2],['check',KY.blurryTip3]]));
add('F4b','Declined · face',ex+f4('r','user',KY.faceA,KY.faceB,'',[['user',KY.faceTip1],['x',KY.faceTip2],['x',KY.faceTip3]]));
add('F4c','Declined · document',ex+f4('r','id',KY.docA,KY.docB,KY.docBody));
add('F4d','Declined · other',ex+f4('r','alert',KY.otherA,KY.otherB,KY.otherBody));
add('F7','Can’t open',ex+b(hero('r',disc('wifioff'))+t(KY.cantA,KY.cantB,'rd')+s(KY.cantBody)+`<div class="chips"><span class="pill">${I('wifioff','s')}${KY.cant1}</span><span class="pill">${I('cam','s')}${KY.cant2}</span></div>`)+ft(cta(KY.tryAgain,'refresh'),lk(KY.help,'chat')));
add('I·free','Free-job notices',b(hero('',ntf('bike',KY.notif1T,KY.notif1B,'width:296px;align-items:flex-start')+ntf('alert',KY.notif0T,KY.notif0B,'width:296px;align-items:flex-start'),300)+`<div class="t">Two nudges, <em>no surprises</em></div>`+s('Sent at 1 free job left and at 0.')));

H.push(sec('Account','Settings, become a rider, delete'));
add('D1','Settings · rider',top()+`<div class="big">Settings</div>`+b(`<div class="cap" style="font-size:12px;font-weight:600;letter-spacing:.06em;color:#5B6670;margin:0 4px 8px">YOU</div><div class="list"><div class="li"><span class="dd ok">${I('user','m')}</span><span class="n">${PD.row}<small>${PD.rowSub}</small></span>${I('chev','m ch')}</div><div class="li"><span class="dd vi">${I('bike','m')}</span><span class="n">${BD.title}</span><span class="v">1 to add</span>${I('chev','m ch')}</div><div class="li"><span class="dd ">${I('globe','m')}</span><span class="n">Language</span><span class="v">English</span>${I('chev','m ch')}</div></div><div style="font-size:12px;font-weight:600;letter-spacing:.06em;color:#5B6670;margin:20px 4px 8px">ALERTS</div><div class="list"><div class="li"><span class="dd ">${I('vol','m')}</span><span class="n">Job alerts<small>Ping and food-offer alarm</small></span><span class="tg"></span></div><div class="li"><span class="dd ">${I('pin','m')}</span><span class="n">Location<small>Needed for jobs</small></span><span class="tg"></span></div><div class="li"><span class="dd ">${I('bell','m')}</span><span class="n">Order updates</span><span class="tg"></span></div></div><div class="list" style="margin-top:16px"><div class="li"><span class="dd ">${I('out','m')}</span><span class="n">Sign out</span></div></div>`));
add('G2','Account · become a rider',greetHd(`<span style="color:#006630;font-weight:600;display:flex;gap:3px;align-items:center">${I('pin','s')}12 Samora Machel Ave</span>`)+b(`<div style="display:flex;gap:12px;align-items:center;margin:-16px 4px 16px"><span class="dd ok" style="width:52px;height:52px;font-weight:700;font-size:18px">TM</span><div><div style="font-weight:700;font-size:17px">Tendai Moyo</div><div style="font-size:14px;color:#5B6670">+263 77 245 1180</div></div></div><div style="position:relative;overflow:hidden;border-radius:24px;background:#ECE8FF;padding:20px"><span style="position:absolute;right:-40px;top:-40px;width:120px;height:120px;border-radius:50%;background:#FFD23F"></span><span style="position:absolute;right:70px;top:24px;width:14px;height:14px;border-radius:50%;background:#FF6B4A"></span><div style="position:relative;font-size:22px;font-weight:700;letter-spacing:-.02em;line-height:1.15">${KY.becomeA}<br><span style="color:#4B2FBF">${KY.becomeB}</span></div><div style="position:relative;font-size:14px;color:#5B6670;margin-top:6px">${KY.becomeBody}</div><button class="cta" style="margin-top:16px">${KY.becomeCta}${I('arrow','m')}</button></div>`));
add('I','Delete account',top()+b(`<div style="margin-top:-24px"></div>`+hero('r',disc('trash'),180)+t('Delete','your account?','rd')+s('Profile, places and order history go for good. Payment records stay as the law needs.')+`<div class="box ok">${I('check','m')}No delivery running</div>`)+ft(cta('Keep my account'),lk('Delete account','','#8F2418')));
H.push(sec('H · Splash','Rider: two steps. 320×640: card sits on the nav bar, wordmark centres in what’s left'));
add('H1','Rider · 360',splash(360,720),{c:'dark'});
add('H2a','320 · 3-button',splash(320,640,{nav:'3'}),{w:320,h:640,c:'dark'});
add('H2b','320 · gesture',splash(320,640,{nav:'g'}),{w:320,h:640,c:'dark'});
add('H2c','320 · 3-button offline',splash(320,640,{nav:'3',offline:1}),{w:320,h:640,c:'dark'});

H.push(sec('Font scale 1.3','Hero shrinks, copy wraps, CTA stays pinned'));
add('P1','fs 1.3',p1(),fs);add('U1','fs 1.3',u1(),fs);add('F4a','fs 1.3',ex+f4('r','cam',KY.blurryA,KY.blurryB,'',[['sun',KY.blurryTip1],['id',KY.blurryTip2],['check',KY.blurryTip3]]),fs);add('D2','fs 1.3',d2(idPh,idWhy),fs);

H.push(sec('320×640','Same layouts, smaller hero'));
add('PC1','320',pc1(),sm);add('P1','320',p1(),sm);add('P9','320',p9(),sm);add('U1','320',u1(),sm);add('F4a','320',ex+f4('r','cam',KY.blurryA,KY.blurryB,'',[['sun',KY.blurryTip1],['id',KY.blurryTip2],['check',KY.blurryTip3]]),sm);add('E1','320',e1(),sm);

const q=new URLSearchParams(location.search).get('screen');
const root=document.getElementById('board');
root.innerHTML=H.join('');
const set=document.body.dataset.set;if(set){const keep=set.split(',');const seen=new Set();root.querySelectorAll('.cell').forEach(c=>{const id=c.dataset.id;if(!keep.includes(id)||seen.has(id)||c.querySelector('.f.fs13,.f.sm'))c.remove();else seen.add(id)});root.querySelectorAll('.sec').forEach(x=>x.remove());root.querySelector('.intro').innerHTML='<h1>First run, redrawn</h1><p>One hero, one bold line, one action. Every state: <a href="First Run v2 - All States.html">All States</a>.</p>'}
if(q){const c=[...root.querySelectorAll('.cell')].find(c=>c.querySelector('.lbl i').textContent===q);if(c){document.body.innerHTML='';document.body.appendChild(c.querySelector('.f'));document.body.style.cssText='margin:0;background:#F6F7F8'}}
})();
