// GENERATED by apps/mobile/scripts/svg-to-rn.mjs — do not edit by hand.
// Source: packages/design/handoff/calm-mint-v2-2026-10/assets (Calm Mint v2 handoff, docs/DESIGN-DEVIATIONS.md D-55).
// Verbatim transcription of the handoff's artwork; regenerate with `node scripts/svg-to-rn.mjs`.
import React from "react";
import Svg, { Circle, ClipPath, Defs, Ellipse, G, Path, Polygon, Rect } from "react-native-svg";

/** `illustrations/hero-rider.svg` — 480×500. Pass the drawn WIDTH; the height follows the artboard. */
export function HeroRiderArt({ width }: { width: number }): React.ReactElement {
  return (
    <Svg width={width} height={(width * 500) / 480} viewBox="0 0 480 500">
      <Defs>
        <ClipPath id="hc">
          <Rect width="480" height="500" rx="40" />
        </ClipPath>
      </Defs>
      <G clipPath="url(#hc)">
        <Rect width="480" height="500" fill="#BDEBFB" />
        <Ellipse cx="90" cy="70" rx="70" ry="26" fill="#fff" />
        <Ellipse cx="130" cy="56" rx="40" ry="24" fill="#fff" />
        <Ellipse cx="390" cy="96" rx="60" ry="20" fill="#fff" />
        <Ellipse cx="420" cy="84" rx="34" ry="20" fill="#fff" />
        <Rect x="20" y="170" width="120" height="220" fill="#8ED8F2" />
        <Rect x="100" y="170" width="40" height="220" fill="#6CC5E8" />
        <Rect x="34" y="190" width="20" height="24" rx="2" fill="#E9F8EF" />
        <Rect x="64" y="190" width="20" height="24" rx="2" fill="#E9F8EF" />
        <Rect x="34" y="230" width="20" height="24" rx="2" fill="#E9F8EF" />
        <Rect x="64" y="230" width="20" height="24" rx="2" fill="#E9F8EF" />
        <Rect x="34" y="270" width="20" height="24" rx="2" fill="#E9F8EF" />
        <Rect x="64" y="270" width="20" height="24" rx="2" fill="#E9F8EF" />
        <Rect x="34" y="310" width="20" height="24" rx="2" fill="#E9F8EF" />
        <Rect x="64" y="310" width="20" height="24" rx="2" fill="#E9F8EF" />
        <Rect x="330" y="140" width="150" height="250" fill="#8ED8F2" />
        <Rect x="330" y="140" width="40" height="250" fill="#6CC5E8" />
        <Rect x="386" y="160" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="420" y="160" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="454" y="160" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="386" y="205" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="420" y="205" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="454" y="205" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="386" y="250" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="420" y="250" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="454" y="250" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="386" y="295" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="420" y="295" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="454" y="295" width="22" height="28" rx="2" fill="#E9F8EF" />
        <Rect x="176" y="250" width="10" height="140" fill="#6B4A3A" />
        <Circle cx="160" cy="236" r="40" fill="#B197FC" />
        <Circle cx="206" cy="226" r="44" fill="#9775FA" />
        <Circle cx="182" cy="198" r="38" fill="#B197FC" />
        <Circle cx="170" cy="222" r="6" fill="#E5DBFF" />
        <Circle cx="210" cy="204" r="5" fill="#E5DBFF" />
        <Circle cx="224" cy="240" r="4" fill="#E5DBFF" />
        <Path d="M0 380h480v120H0Z" fill="#3B4552" />
        <Path d="M0 380h480v10H0Z" fill="#FFD23F" />
        <Path d="M40 450h70M170 450h70M300 450h70M430 450h60" stroke="#FFD23F" strokeWidth="7" strokeLinecap="round" />
        <G strokeLinecap="round" fill="none">
          <Path d="M360 250c40-20 70 20 130-10" stroke="#FF6B4A" strokeWidth="16" />
          <Path d="M380 290c40-16 60 22 110-4" stroke="#FFD23F" strokeWidth="13" />
          <Path d="M400 330c30-12 50 16 90-2" stroke="#fff" strokeWidth="9" opacity=".85" />
          <Path d="M350 214c50-24 80 10 140-18" stroke="#FFD23F" strokeWidth="7" opacity=".8" />
        </G>
        <G stroke="#fff" strokeWidth="3" strokeLinecap="round" opacity=".8">
          <Path d="M20 120l80-30M40 150l50-18M410 360l60-22M430 400l40-14" />
        </G>
        <Ellipse cx="250" cy="455" rx="170" ry="16" fill="#2B3440" opacity=".45" />
        <Circle cx="345" cy="398" r="58" fill="#2B3440" />
        <Circle cx="345" cy="398" r="34" fill="#E9EDF2" />
        <Circle cx="345" cy="398" r="14" fill="#ADB5BD" />
        <Circle cx="345" cy="398" r="6" fill="#495057" />
        <Circle cx="140" cy="402" r="55" fill="#2B3440" />
        <Circle cx="140" cy="402" r="32" fill="#E9EDF2" />
        <Circle cx="140" cy="402" r="13" fill="#ADB5BD" />
        <Circle cx="140" cy="402" r="6" fill="#495057" />
        <Path d="M280 348 345 398" stroke="#495057" strokeWidth="12" strokeLinecap="round" />
        <Path d="M300 370h60" stroke="#ADB5BD" strokeWidth="9" strokeLinecap="round" />
        <Path d="M165 262 140 402" stroke="#ADB5BD" strokeWidth="10" strokeLinecap="round" />
        <Path d="M92 382a50 50 0 0 1 86-18l-10 8a38 38 0 0 0-66 14Z" fill="#00B14F" />
        <Path d="M300 352a52 52 0 0 1 96 18l-12 2a40 40 0 0 0-74-12Z" fill="#00913C" />
        <Rect x="196" y="318" width="96" height="50" rx="10" fill="#495057" />
        <Rect x="206" y="328" width="40" height="30" rx="5" fill="#6C757D" />
        <Path d="M170 282q10-14 40-12l80 10q18 4 12 26l-8 18H186q-20-2-16-42Z" fill="#00B14F" />
        <Path d="M240 276l50 4q18 4 12 26l-8 18h-54Z" fill="#00913C" />
        <Path d="M258 282h60q8 0 6 8l-4 8h-64Z" fill="#2B3440" />
        <Circle cx="164" cy="290" r="14" fill="#FFD23F" />
        <Circle cx="164" cy="290" r="7" fill="#fff" />
        <Path d="M150 258l40 12" stroke="#2B3440" strokeWidth="7" strokeLinecap="round" />
        <Path d="M152 256l-6-14" stroke="#2B3440" strokeWidth="4" strokeLinecap="round" />
        <Circle cx="144" cy="238" r="7" fill="#ADB5BD" />
        <Path d="M295 200h96a6 6 0 0 1 6 6v80a6 6 0 0 1-6 6h-96a6 6 0 0 1-6-6v-80a6 6 0 0 1 6-6Z" fill="#00B14F" />
        <Path d="M397 206l20-14v78l-20 16Z" fill="#00913C" />
        <Path d="M295 200l20-14h102l-20 14Z" fill="#3DD37A" />
        <G transform="translate(318 218) scale(.56)">
          <Polygon points="28,6 58,32 38,42" fill="#fff" />
          <Polygon points="90,26 14,52 48,60" fill="#fff" />
          <Polygon points="90,26 48,60 42,84" fill="#E9F8EF" />
        </G>
        <Path d="M296 216l-54 10" stroke="#2B3440" strokeWidth="5" strokeLinecap="round" />
        <Path d="M282 300 228 324" stroke="#34404F" strokeWidth="28" strokeLinecap="round" />
        <Path d="M228 324 248 372" stroke="#34404F" strokeWidth="22" strokeLinecap="round" />
        <Path d="M236 380q16-10 34 0v8h-34Z" fill="#fff" />
        <Path d="M236 386h34v4h-34Z" fill="#FFD23F" />
        <Path d="M204 214q28-16 56-2l46 80q-18 20-44 14l-58-80Z" fill="#00B14F" />
        <Path d="M236 206q14 0 24 6l46 80q-10 12-24 14Z" fill="#00913C" />
        <Path d="M214 230l40 72" stroke="#FFD23F" strokeWidth="4" />
        <Path d="M222 228 176 262" stroke="#00B14F" strokeWidth="22" strokeLinecap="round" />
        <Path d="M226 236 184 268" stroke="#00913C" strokeWidth="8" strokeLinecap="round" opacity=".6" />
        <Circle cx="170" cy="266" r="11" fill="#2B3440" />
        <Rect x="200" y="196" width="18" height="18" rx="4" fill="#A8703F" />
        <Circle cx="214" cy="166" r="36" fill="#00B14F" />
        <Path d="M214 130a36 36 0 0 1 36 36 36 36 0 0 1-20 32Z" fill="#00913C" />
        <Ellipse cx="200" cy="182" rx="19" ry="22" fill="#C68B59" />
        <Path d="M200 160a19 22 0 0 0-19 22 19 22 0 0 0 5 14q-2-20 14-36Z" fill="#A8703F" opacity=".5" />
        <Path d="M180 164q22-12 46 0l-2 8q-22-10-42 0Z" fill="#2B3440" />
        <Path d="M186 154q20-10 40 0" stroke="#5FD68F" strokeWidth="3" fill="none" strokeLinecap="round" />
        <Circle cx="192" cy="180" r="2.6" fill="#2B3440" />
        <Circle cx="206" cy="180" r="2.6" fill="#2B3440" />
        <Path d="M190 192q8 7 16 0" fill="#fff" stroke="#7A4A2A" strokeWidth="1.5" />
      </G>
    </Svg>
  );
}
