// GENERATED by apps/mobile/scripts/svg-to-rn.mjs — do not edit by hand.
// Source: packages/design/handoff/calm-mint-v2-2026-10/assets (Calm Mint v2 handoff, docs/DESIGN-DEVIATIONS.md D-55).
// Verbatim transcription of the handoff's artwork; regenerate with `node scripts/svg-to-rn.mjs`.
import React from "react";
import Svg, { Circle, Ellipse, G, Path, Polygon, Rect } from "react-native-svg";

/** `illustrations/biz-scooter-rider.svg` — 460×460. Pass the drawn WIDTH; the height follows the artboard. */
export function ScooterRiderArt({ width }: { width: number }): React.ReactElement {
  return (
    <Svg width={width} height={(width * 460) / 460} viewBox="0 0 460 460">
      <G fill="none">
        <Rect width="460" height="460" rx="36" fill="#FF6B4A" />
        <G fill="#FFF3EC" opacity=".9">
          <Rect x="148" y="98" width="178" height="9" rx="4.5" />
          <Rect x="110" y="124" width="200" height="8" rx="4" />
          <Rect x="122" y="148" width="150" height="8" rx="4" />
          <Rect x="104" y="172" width="120" height="7" rx="3.5" />
          <Rect x="64" y="198" width="100" height="6" rx="3" />
          <Rect x="60" y="238" width="70" height="6" rx="3" />
          <Rect x="332" y="112" width="30" height="7" rx="3.5" />
        </G>
        <Ellipse cx="220" cy="372" rx="178" ry="9" fill="#D84A2E" />
        <Rect x="40" y="366" width="380" height="3" rx="1.5" fill="#C43E24" />
        <G fill="#FFD23F">
          <Circle cx="372" cy="340" r="3" />
          <Circle cx="384" cy="352" r="2.2" />
          <Circle cx="366" cy="356" r="2" />
          <Circle cx="392" cy="336" r="1.8" />
        </G>
        <G>
          <Circle cx="320" cy="322" r="46" fill="#14181B" />
          <Circle cx="320" cy="322" r="33" fill="#2E343A" />
          <Circle cx="320" cy="322" r="27" fill="#C9CED3" />
          <Circle cx="320" cy="322" r="23" fill="#9AA2AA" />
          <G stroke="#E4E7EA" strokeWidth="2.5">
            <Path d="M320 299v46M297 322h46M304 306l32 32M336 306l-32 32" />
          </G>
          <Circle cx="320" cy="322" r="8" fill="#14181B" />
          <Circle cx="320" cy="322" r="3.5" fill="#C9CED3" />
        </G>
        <G>
          <Circle cx="100" cy="324" r="44" fill="#14181B" />
          <Circle cx="100" cy="324" r="31" fill="#2E343A" />
          <Circle cx="100" cy="324" r="25" fill="#C9CED3" />
          <Circle cx="100" cy="324" r="21" fill="#9AA2AA" />
          <G stroke="#E4E7EA" strokeWidth="2.5">
            <Path d="M100 303v42M79 324h42M85 309l30 30M115 309l-30 30" />
          </G>
          <Circle cx="100" cy="324" r="10" fill="#6B737B" />
          <Circle cx="100" cy="324" r="4" fill="#14181B" />
        </G>
        <Path d="M270 292q50-34 98 4l-8 12q-38-28-82-2z" fill="#E7E1D6" />
        <Path d="M222 262 356 248q30 6 30 42l-10 22-36 8q-20-36-60-24l-38 30-26-10z" fill="#F7F3EA" />
        <Path d="M232 300q60-10 144-16l-4 22-32 10q-20-30-58-20l-30 20z" fill="#E4DCCD" />
        <Path d="M258 270 350 262q16 2 18 18l-86 10q-20-4-24-28z" fill="#FFD23F" />
        <Path d="M282 290l86-10q-2 10-8 14l-72 8z" fill="#E8AE12" />
        <Rect x="340" y="266" width="22" height="7" rx="3" fill="#FF6B4A" />
        <Path d="M146 328h130l6 14H146z" fill="#14181B" />
        <Path d="M150 322h122l4 8H150z" fill="#3A4046" />
        <Path d="M134 196q22-4 36 18l38 104q-8 14-40 20l-18-6q-26-40-56-64-8-34 40-72z" fill="#F7F3EA" />
        <Path d="M170 214l38 104q-8 14-40 20l-4-2q24-8 28-18l-36-96z" fill="#E4DCCD" />
        <Path d="M104 250q30-8 50 14l20 52-14 4q-26-44-60-54z" fill="#FFD23F" />
        <Path d="M56 304q40-52 96-16l-6 12q-46-30-80 10z" fill="#FFD23F" />
        <Path d="M66 310q34-40 80-10l-4 6q-40-26-72 8z" fill="#E8AE12" />
        <Path d="M108 196q10-16 30-12l6 22q-18 0-34 4z" fill="#14181B" />
        <Ellipse cx="116" cy="198" rx="12" ry="10" fill="#FFF7C2" />
        <Ellipse cx="113" cy="196" rx="5" ry="4" fill="#fff" />
        <Path d="M138 178l38 2" stroke="#14181B" strokeWidth="6" strokeLinecap="round" />
        <Path d="M150 176l-6-26" stroke="#14181B" strokeWidth="3" strokeLinecap="round" />
        <Ellipse cx="143" cy="146" rx="8" ry="5" fill="#2E343A" />
        <Path d="M224 254q60-18 128-10l2 14-126 14z" fill="#14181B" />
        <Path d="M232 256q56-14 116-8" stroke="#3A4046" strokeWidth="3" strokeLinecap="round" />
        <Rect x="296" y="228" width="92" height="10" rx="3" fill="#14181B" />
        <Path d="M304 238v12M378 238v10" stroke="#14181B" strokeWidth="5" />
        <Path d="M300 150h82q10 0 10 10v68h-92z" fill="#FFD23F" />
        <Path d="M372 150h10q10 0 10 10v68h-20z" fill="#E8AE12" />
        <Path d="M300 150h92v14h-92z" fill="#FFE27A" />
        <Path d="M300 164h92" stroke="#E8AE12" strokeWidth="2" />
        <G transform="translate(314 174) scale(.46)">
          <Polygon points="28,6 58,32 38,42" fill="#00B14F" />
          <Polygon points="90,26 14,52 48,60" fill="#00B14F" />
          <Polygon points="90,26 48,60 42,84" fill="#009D3B" />
          <Path d="M90 26 L48 60" stroke="#FFD23F" strokeWidth="2.4" />
          <Path d="M70.5 30.2 L81.5 43.8" stroke="#FFD23F" strokeWidth="2.4" />
        </G>
        <Path d="M288 150q12-6 20 0v78h-20z" fill="#0A5A34" />
        <Path d="M292 212q10 36-20 42l-58 10q-22 2-22-16 2-14 22-18l46-8z" fill="#2B3A55" />
        <Path d="M280 244q-6 10-18 12l-50 8q-14 2-20-6 10 2 22 0l50-8q10-2 16-6z" fill="#1E2A40" />
        <Path d="M194 246l30-2 18 66-26 6z" fill="#2B3A55" />
        <Path d="M226 246l16 64-10 3-16-66z" fill="#1E2A40" />
        <Path d="M210 310h34q20 2 22 14v6h-60q-4-10 4-20z" fill="#F7F7F2" />
        <Path d="M206 326h60v5h-60z" fill="#C9CED3" />
        <Path d="M228 314l6 8M238 312l6 8" stroke="#9AA2AA" strokeWidth="2" />
        <Path d="M208 138q48-16 86 16 14 34 4 66l-60 10q-22-26-34-60z" fill="#00B14F" />
        <Path d="M270 144q24 10 24 10 14 34 4 66l-28 5q14-40 0-81z" fill="#009443" />
        <Path d="M212 144q18-8 34 0l-10 30q-18 4-30-8z" fill="#00C257" />
        <Path d="M270 146l24 44" stroke="#0A5A34" strokeWidth="6" strokeLinecap="round" />
        <Rect x="212" y="130" width="18" height="14" rx="5" fill="#8B5A3C" />
        <Path d="M214 150q18-6 28 8l-20 34-22-12z" fill="#00B14F" />
        <Path d="M226 156q12 2 16 8l-20 28-8-4z" fill="#009443" />
        <Path d="M202 176l22 12-26 12-16-10z" fill="#8B5A3C" />
        <Path d="M188 186l18 12-10 6-14-10z" fill="#6E4630" />
        <Rect x="162" y="172" width="26" height="20" rx="8" fill="#F7F7F2" />
        <Rect x="166" y="186" width="18" height="6" rx="3" fill="#C9CED3" />
        <Circle cx="222" cy="106" r="42" fill="#F7F7F2" />
        <Path d="M256 82q16 30-2 58-18 14-38 8 30-12 40-66z" fill="#DAD6CC" />
        <Path d="M198 72q20-14 44-6" stroke="#fff" strokeWidth="6" strokeLinecap="round" />
        <Path d="M181 98q12-18 50-10l4 34q-24 10-52 0-6-12-2-24z" fill="#14181B" />
        <Path d="M190 96q14-8 32-6" stroke="#4A5560" strokeWidth="4" strokeLinecap="round" />
        <Path d="M216 90l14 2 2 22-12 4z" fill="#2E343A" />
        <Path d="M188 124q18 12 40 4l-2 14q-22 6-36-4z" fill="#DAD6CC" />
        <Rect x="240" y="98" width="8" height="18" rx="4" fill="#00B14F" />
      </G>
    </Svg>
  );
}
