// GENERATED by apps/mobile/scripts/svg-to-rn.mjs — do not edit by hand.
// Source: packages/design/handoff/calm-mint-v2-2026-10/assets (Calm Mint v2 handoff, docs/DESIGN-DEVIATIONS.md D-55).
// Verbatim transcription of the handoff's artwork; regenerate with `node scripts/svg-to-rn.mjs`.
import React from "react";
import Svg, { Circle, G, Path, Rect } from "react-native-svg";

/** `service-icons/v2/send.svg` — 64×64. Pass the drawn WIDTH; the height follows the artboard. */
export function SendStickerV2({ width }: { width: number }): React.ReactElement {
  return (
    <Svg width={width} height={(width * 64) / 64} viewBox="0 0 64 64">
      <Rect x="3" y="24" width="9" height="3" rx="1.5" fill="#B9E8CC" />
      <Rect x="1" y="32" width="11" height="3" rx="1.5" fill="#B9E8CC" />
      <Rect x="5" y="40" width="7" height="3" rx="1.5" fill="#B9E8CC" />
      <Path d="M16 22 38 14 60 22 38 30Z" fill="#3CCB74" />
      <Path d="M16 22 38 30V56L16 47Z" fill="#00B14F" />
      <Path d="M38 30 60 22V47L38 56Z" fill="#00913C" />
      <Path d="M27 18 49 26V34L44 36V28L22 20Z" fill="#FFD23F" />
      <Path d="M24 35l6-2-3 7-1-3-3-1Z" fill="#FFFFFF" />
      <Circle cx="56" cy="9" r="3" fill="#FF6B4A" />
    </Svg>
  );
}

/** `service-icons/v2/restaurants.svg` — 64×64. Pass the drawn WIDTH; the height follows the artboard. */
export function RestaurantsSticker({ width }: { width: number }): React.ReactElement {
  return (
    <Svg width={width} height={(width * 64) / 64} viewBox="0 0 64 64">
      <Path d="M44 6 30 26" stroke="#14181B" strokeWidth="3" strokeLinecap="round" />
      <Path d="M52 9 34 27" stroke="#14181B" strokeWidth="3" strokeLinecap="round" />
      <Path d="M14 28h36" stroke="#FFD23F" strokeWidth="6" strokeLinecap="round" />
      <Path d="M18 24c4-4 8 4 12 0s8 4 12 0" fill="none" stroke="#FFD23F" strokeWidth="3" strokeLinecap="round" />
      <Path d="M6 30h52c0 14-11 24-26 24S6 44 6 30Z" fill="#FF6B4A" />
      <Path d="M6 30h52c0 3-.5 5-1.3 7H7.3C6.5 35 6 33 6 30Z" fill="#E5533A" />
      <Rect x="22" y="54" width="20" height="5" rx="2.5" fill="#E5533A" />
      <Circle cx="10" cy="12" r="2.5" fill="#00B14F" />
      <Circle cx="20" cy="40" r="3" fill="#FFE7E0" />
    </Svg>
  );
}

/** `service-icons/v2/shops.svg` — 64×64. Pass the drawn WIDTH; the height follows the artboard. */
export function ShopsSticker({ width }: { width: number }): React.ReactElement {
  return (
    <Svg width={width} height={(width * 64) / 64} viewBox="0 0 64 64">
      <Rect x="10" y="26" width="44" height="32" rx="3" fill="#4B2FBF" />
      <Path d="M6 14h52l2 12H4Z" fill="#FFFFFF" />
      <Path d="M6 14h9l-2 12H4Z" fill="#FF8AC5" />
      <Path d="M24 14h8v12h-9Z" fill="#FF8AC5" />
      <Path d="M41 14h8l2 12h-9Z" fill="#FF8AC5" />
      <Path d="M4 26h56a0 0 0 0 1 0 0c0 3-2.5 5-5.5 5S49 29 49 26c0 3-2.5 5-5.5 5S38 29 38 26c0 3-2.5 5-5.5 5S27 29 27 26c0 3-2.5 5-5.5 5S16 29 16 26c0 3-2.5 5-5.5 5S4 29 4 26Z" fill="#FF8AC5" />
      <Rect x="16" y="36" width="14" height="22" rx="2" fill="#3EC1F3" />
      <Rect x="35" y="36" width="13" height="11" rx="2" fill="#FFD23F" />
      <Circle cx="27" cy="48" r="1.5" fill="#14181B" />
      <Rect x="10" y="8" width="44" height="6" rx="3" fill="#00B14F" />
    </Svg>
  );
}

/** `service-icons/v2/pharmacy.svg` — 64×64. Pass the drawn WIDTH; the height follows the artboard. */
export function PharmacyStickerV2({ width }: { width: number }): React.ReactElement {
  return (
    <Svg width={width} height={(width * 64) / 64} viewBox="0 0 64 64">
      <Rect x="12" y="8" width="28" height="9" rx="3" fill="#FF6B4A" />
      <Rect x="10" y="16" width="32" height="42" rx="7" fill="#FFFFFF" />
      <Rect x="10" y="16" width="32" height="42" rx="7" fill="none" stroke="#C5E9DF" strokeWidth="3" />
      <Rect x="22" y="28" width="8" height="20" rx="2" fill="#00B14F" />
      <Rect x="16" y="34" width="20" height="8" rx="2" fill="#00B14F" />
      <G transform="rotate(-35 50 44)">
        <Rect x="40" y="38" width="22" height="11" rx="5.5" fill="#3EC1F3" />
        <Path d="M51 38h5.5a5.5 5.5 0 0 1 0 11H51Z" fill="#FFD23F" />
      </G>
      <Circle cx="52" cy="14" r="2.5" fill="#FF8AC5" />
    </Svg>
  );
}
