// GENERATED by apps/mobile/scripts/svg-to-rn.mjs — do not edit by hand.
// Source: packages/design/handoff/calm-mint-v2-2026-10/assets (Calm Mint v2 handoff, docs/DESIGN-DEVIATIONS.md D-55).
// Verbatim transcription of the handoff's artwork; regenerate with `node scripts/svg-to-rn.mjs`.
import React from "react";
import Svg, { Circle, Ellipse, Path } from "react-native-svg";

/** `illustrations/trust-tracking.svg` — 120×100. Pass the drawn WIDTH; the height follows the artboard. */
export function TrustTrackingArt({ width }: { width: number }): React.ReactElement {
  return (
    <Svg width={width} height={(width * 100) / 120} viewBox="0 0 120 100">
      <Ellipse cx="60" cy="91" rx="20" ry="4.5" fill="#DDE3EA" />
      <Path d="M26 28a26 26 0 0 0 0 26M16 20a38 38 0 0 0 0 42" fill="none" stroke="#FF6B4A" strokeWidth="4" strokeLinecap="round" />
      <Path d="M94 28a26 26 0 0 1 0 26M104 20a38 38 0 0 1 0 42" fill="none" stroke="#FF6B4A" strokeWidth="4" strokeLinecap="round" />
      <Path d="M60 10a29 29 0 0 1 29 29c0 20-22 44-26.5 48.5a3.5 3.5 0 0 1-5 0C53 83 31 59 31 39a29 29 0 0 1 29-29Z" fill="#00B14F" />
      <Path d="M60 10a29 29 0 0 1 29 29c0 20-22 44-26.5 48.5A3.5 3.5 0 0 1 60 88.5Z" fill="#00913C" />
      <Circle cx="60" cy="39" r="13" fill="#fff" />
      <Circle cx="60" cy="39" r="9" fill="#FF9F43" />
      <Path d="M40 30a22 22 0 0 1 8-11" fill="none" stroke="#5FD68F" strokeWidth="3" strokeLinecap="round" />
    </Svg>
  );
}
