// GENERATED by apps/mobile/scripts/svg-to-rn.mjs — do not edit by hand.
// Source: packages/design/handoff/calm-mint-v2-2026-10/assets (Calm Mint v2 handoff, docs/DESIGN-DEVIATIONS.md D-55).
// Verbatim transcription of the handoff's artwork; regenerate with `node scripts/svg-to-rn.mjs`.
import React from "react";
import Svg, { Circle, Ellipse, Path } from "react-native-svg";

/** `illustrations/trust-verified.svg` — 120×100. Pass the drawn WIDTH; the height follows the artboard. */
export function TrustVerifiedArt({ width }: { width: number }): React.ReactElement {
  return (
    <Svg width={width} height={(width * 100) / 120} viewBox="0 0 120 100">
      <Path d="M20 26Q20 30 24 30Q20 30 20 34Q20 30 16 30Q20 30 20 26Z" fill="#FFC940" />
      <Path d="M100 20.5Q100 24 103.5 24Q100 24 100 27.5Q100 24 96.5 24Q100 24 100 20.5Z" fill="#FF6B4A" />
      <Path d="M98 77Q98 80 101 80Q98 80 98 83Q98 80 95 80Q98 80 98 77Z" fill="#00B14F" />
      <Path d="M44 64 33 92l9-4 5 8 10-26Z" fill="#FF6B4A" />
      <Path d="M76 64l11 28-9-4-5 8-10-26Z" fill="#E0472A" />
      <Path d="M60 8 88 19v26c0 21-13 35-28 41-15-6-28-20-28-41V19Z" fill="#FFC940" />
      <Path d="M60 8 88 19v26c0 21-13 35-28 41Z" fill="#F2A900" />
      <Circle cx="40" cy="26" r="2.2" fill="#FFE08A" />
      <Ellipse cx="39" cy="34" rx="2" ry="3.5" fill="#FFE08A" />
      <Circle cx="60" cy="44" r="17" fill="#fff" />
      <Path d="M77 44a17 17 0 0 1-34 0q17 11 34 0Z" fill="#DDE3EA" />
      <Path d="m51 44 6.5 6.5L70 38" fill="none" stroke="#00B14F" strokeWidth="5.5" strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}
