/**
 * RENDERED conformance — the CI-blocking half of the parity guardrail suite.
 *
 * The static guardrails read source: token values, the screen inventory, the mock's own AST. None of
 * them can see what a screen ACTUALLY paints once its data arrives — which conditional branch wins,
 * what the live wiring interpolates into a string, whether the app invented copy the mock never drew.
 * That blind spot is how the launcher home shipped ONE generic card reading "Delivery in progress"
 * while the mock draws TWO service-specific cards ("Sadza Republic · 6 min away" / "Cash at the door
 * · $15.50" / "Parcel to Msasa · rider 4 min away" / "Delivery code 4192 · $3.36").
 *
 * So this test mounts the REAL screen with the REAL parity fixture (the same
 * tools/parity/mobile/fixtures/*.mjs the screenshot lane stages — never a second copy of the data)
 * and compares its rendered text sequence, in order and in groups, against the expectation extracted
 * from the design mock (tools/parity/expected/<key>.json, committed, regenerated by
 * `node tools/parity/extract-expected.mjs`).
 *
 * No browser is involved here on purpose: browser rendering is environment-sensitive, which is why
 * the parity-render CI job is continue-on-error. The browser half runs offline and commits its
 * output; THIS half blocks.
 *
 * Escapes are per-string and reviewable, never blanket:
 *   - `dynamic` in the expected JSON — a mock string a fixture cannot pin (a geolocated address, a
 *     live clock). Requires a regex the app string must satisfy, plus a written reason.
 *   - `extra` in the expected JSON — an app string the mock does not draw. "Not drawn ⇒ not
 *     rendered" means the default is to DELETE it from the screen; an entry here is a reviewed
 *     exception with a reason.
 *   - tools/parity/rendered-conformance.pending.json — a wired+fixtured key not yet asserted at all,
 *     with an honest reason. A key that is in neither the expected set nor pending FAILS: no screen
 *     is silently uncovered.
 */
import React from "react";
import renderer, { act } from "react-test-renderer";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { fromTestTree, type TestNode } from "../rendered-tree";

/* ───────────────────────────── device/module shims ─────────────────────────────
 * Deliberately the same surface as tools/parity/mobile/shims/*, so a fixture stages the screen in
 * jest exactly as it does in the browser renderer. Anything richer would make the two lanes disagree.
 */

const secureStore: Record<string, string> = {};
jest.mock("expo-secure-store", () => ({
  getItemAsync: async (k: string) => secureStore[k] ?? null,
  setItemAsync: async (k: string, v: string) => {
    secureStore[k] = String(v);
  },
  deleteItemAsync: async (k: string) => {
    delete secureStore[k];
  },
}));

// Mirrors tools/parity/mobile/shims/expo-location.js: permission state answers from the fixture's
// `__PARITY_PERMISSIONS` seed (the same key the browser shim reads), so LJ.settings_perms can stage
// the denied device the mock draws in BOTH lanes.
const parityPermissions = (): Record<string, string> =>
  ((globalThis as { window?: { __PARITY_PERMISSIONS?: Record<string, string> } }).window?.__PARITY_PERMISSIONS ??
    (globalThis as { __PARITY_PERMISSIONS?: Record<string, string> }).__PARITY_PERMISSIONS ??
    {});
jest.mock("expo-location", () => ({
  Accuracy: { Lowest: 1, Low: 2, Balanced: 3, High: 4, Highest: 5, BestForNavigation: 6 },
  requestForegroundPermissionsAsync: async () => ({ status: "granted", granted: true, canAskAgain: true }),
  getForegroundPermissionsAsync: async () => {
    const status = parityPermissions().location || "granted";
    return { status, granted: status === "granted", canAskAgain: status !== "never" };
  },
  getCurrentPositionAsync: async () => ({ coords: { latitude: -17.8292, longitude: 31.0522, accuracy: 5 }, timestamp: 0 }),
  getLastKnownPositionAsync: async () => null,
  hasServicesEnabledAsync: async () => true,
}));

// Mirrors tools/parity/mobile/shims/expo-notifications.js for the calls screens make at mount (the
// cold-start push read in app/index-adjacent modules, the settings notifications row).
jest.mock("expo-notifications", () => ({
  getLastNotificationResponseAsync: async () => null,
  getPermissionsAsync: async () => {
    const status = parityPermissions().notifications || "granted";
    return { status, granted: status === "granted", canAskAgain: status !== "never" };
  },
  requestPermissionsAsync: async () => ({ status: "granted", granted: true }),
  setNotificationHandler: () => {},
  addNotificationResponseReceivedListener: () => ({ remove() {} }),
  addNotificationReceivedListener: () => ({ remove() {} }),
  setNotificationChannelAsync: async () => {},
  getExpoPushTokenAsync: async () => ({ data: "ExponentPushToken[parity]" }),
  AndroidImportance: { MAX: 5, HIGH: 4, DEFAULT: 3 },
}));

jest.mock("expo-router", () => {
  const R = require("react");
  const noop = (): undefined => undefined;
  const params = (): Record<string, unknown> =>
    ((globalThis as Record<string, unknown>).__PARITY_ROUTE_PARAMS as Record<string, unknown>) || {};
  const router = {
    push: noop,
    replace: noop,
    back: noop,
    navigate: noop,
    setParams: noop,
    dismiss: noop,
    dismissAll: noop,
    canGoBack: () => false,
  };
  const passthrough = ({ children }: { children: React.ReactNode }) => R.createElement(R.Fragment, null, children);
  return {
    useRouter: () => router,
    router,
    useLocalSearchParams: params,
    useGlobalSearchParams: params,
    useSegments: () => [],
    usePathname: () => "/",
    useFocusEffect: (cb: () => void | (() => void)) => {
      R.useEffect(() => (typeof cb === "function" ? cb() : undefined), []);
    },
    useNavigation: () => ({ setOptions: noop, navigate: noop, goBack: noop, addListener: () => noop }),
    Link: passthrough,
    Redirect: () => null,
    Slot: passthrough,
    Stack: Object.assign(passthrough, { Screen: () => null }),
    Tabs: Object.assign(passthrough, { Screen: () => null }),
    SplashScreen: { preventAutoHideAsync: noop, hideAsync: noop },
  };
});

jest.mock("react-native-maps", () => {
  const R = require("react");
  const { View } = require("react-native");
  const MapView = R.forwardRef((props: Record<string, unknown>, ref: unknown) => {
    R.useImperativeHandle(ref, () => ({
      fitToCoordinates() {},
      fitToSuppliedMarkers() {},
      fitToElements() {},
      animateToRegion() {},
      animateCamera() {},
      setCamera() {},
      getCamera: () => Promise.resolve({}),
      getMapBoundaries: () => Promise.resolve({}),
    }));
    return R.createElement(View, props, (props as { children?: React.ReactNode }).children);
  });
  const Nothing = () => null;
  return {
    __esModule: true,
    default: MapView,
    Marker: Nothing,
    MarkerAnimated: Nothing,
    Callout: Nothing,
    Polyline: Nothing,
    Circle: Nothing,
    Polygon: Nothing,
    Overlay: Nothing,
    PROVIDER_GOOGLE: "google",
    PROVIDER_DEFAULT: undefined,
    AnimatedRegion: class {
      timing() {
        return { start: () => undefined };
      }
      setValue() {}
    },
  };
});

jest.mock("socket.io-client", () => ({
  io: () => ({ on: () => undefined, off: () => undefined, emit: () => undefined, close: () => undefined, disconnect: () => undefined, connected: false }),
}));

/* ───────────────────────────── registry + expectations ───────────────────────────── */

const path = require("path");
const fs = require("fs");
const REPO = path.resolve(__dirname, "../../../../..");
const PARITY = path.join(REPO, "tools/parity");
const MOBILE = path.join(REPO, "apps/mobile");
const EXPECTED_DIR = path.join(PARITY, "expected");

// The shared normalizer + the app-target registry are the SAME modules the extractor uses.
const { collapse, flattenTexts, conformance, formatReport } = require(path.join(PARITY, "lib/rendered-tree.mjs"));
const { APP_TARGETS } = require(path.join(PARITY, "app-targets.mjs"));
const PENDING = JSON.parse(fs.readFileSync(path.join(PARITY, "rendered-conformance.pending.json"), "utf8"));

interface Expected {
  key: string;
  component: string;
  fixture: string;
  texts: string[];
  textPaths: string[];
  groups: number[][];
  dynamic: { mock: string; match: string; reason: string; ref?: string }[];
  extra: { text: string; reason: string; ref?: string }[];
  undrawn: { mock: string; reason: string; ref?: string }[];
}

/** Every wired mobile screen that has a fixture — the population this guardrail must account for. */
const WIRED: string[] = Object.entries(APP_TARGETS as Record<string, { kind: string; fixture?: string }>)
  .filter(([, t]) => t.kind === "mobile" && !!t.fixture)
  .map(([k]) => k)
  .sort();

const PENDING_KEYS: Record<string, string> = PENDING.keys || {};
const COVERED = WIRED.filter((k) => !(k in PENDING_KEYS));

const METRICS = { insets: { top: 0, left: 0, right: 0, bottom: 0 }, frame: { x: 0, y: 0, width: 360, height: 720 } };

function loadExpected(key: string): Expected {
  return JSON.parse(fs.readFileSync(path.join(EXPECTED_DIR, `${key}.json`), "utf8")) as Expected;
}

/** Mount one wired screen with its parity fixture and return the normalized rendered tree. */
async function renderWired(key: string, imageLabels: Set<string>): Promise<{ texts: { text: string; path: string }[] }> {
  const target = (APP_TARGETS as Record<string, { component: string; fixture: string } | undefined>)[key];
  if (!target) throw new Error(`rendered conformance: ${key} has no app target`);
  // The fixture installs its fetch router / seeds SecureStore / sets route params at module scope,
  // so it must be required immediately before the mount it stages.
  delete (globalThis as Record<string, unknown>).__PARITY_ROUTE_PARAMS;
  const fixtureModule = require(path.join(PARITY, "mobile/fixtures", `${target.fixture}.mjs`));
  const fixture = (fixtureModule.default || fixtureModule) as {
    wrap?: (el: React.ReactElement) => React.ReactElement;
    props?: Record<string, unknown>;
  };
  const Screen = require(path.join(MOBILE, target.component)).default as React.ComponentType<Record<string, unknown>>;

  let tree!: renderer.ReactTestRenderer;
  await act(async () => {
    const el = React.createElement(Screen, fixture.props || {});
    tree = renderer.create(
      <SafeAreaProvider initialMetrics={METRICS}>{fixture.wrap ? fixture.wrap(el) : el}</SafeAreaProvider>,
    );
  });
  // Settle the fixture's routed fetches and the app's own deferred reads (use-feature-flags fires a
  // beat after mount, exactly as the browser renderer waits for).
  for (const ms of [0, 50, 300, 50]) {
    await act(async () => {
      await new Promise((r) => setTimeout(r, ms));
    });
  }

  const json = tree.toJSON() as unknown as TestNode | TestNode[] | null;
  const raw = Array.isArray(json)
    ? { role: "container" as const, children: json.map(fromTestTree).filter(Boolean) as never[] }
    : fromTestTree(json);
  const normalized = collapse(raw) || { role: "container", children: [] };
  act(() => tree.unmount());
  return { texts: flattenTexts(normalized, { imageLabels }) };
}

/* ───────────────────────────── the guardrail ───────────────────────────── */

// Each fixture swaps `globalThis.fetch` for its own router at import; put the environment back so a
// later suite in the same worker can never inherit one screen's staged API.
const realFetch = globalThis.fetch;
afterAll(() => {
  globalThis.fetch = realFetch;
  delete (globalThis as Record<string, unknown>).__PARITY_ROUTE_PARAMS;
});

describe("rendered conformance — coverage ledger", () => {
  it("every wired+fixtured mobile screen is either asserted or explicitly pending", () => {
    const gaps: string[] = [];
    for (const key of WIRED) {
      if (key in PENDING_KEYS) continue;
      if (!fs.existsSync(path.join(EXPECTED_DIR, `${key}.json`))) gaps.push(key);
    }
    expect(gaps).toEqual([]);
  });

  it("pending entries name a real wired screen and carry an honest reason", () => {
    const problems: string[] = [];
    for (const [key, reason] of Object.entries(PENDING_KEYS)) {
      if (!WIRED.includes(key)) problems.push(`${key}: not a wired+fixtured mobile target (stale entry)`);
      if (typeof reason !== "string" || reason.trim().length < 40) {
        problems.push(`${key}: reason must be a real explanation (>=40 chars), got ${JSON.stringify(reason)}`);
      }
    }
    expect(problems).toEqual([]);
  });

  it("asserts at least the launcher home plus five more wired screens", () => {
    expect(COVERED).toContain("RC.home");
    expect(COVERED.length).toBeGreaterThanOrEqual(6);
  });

  it("every per-string escape carries a real reason and a tracked reference", () => {
    const problems: string[] = [];
    for (const key of COVERED) {
      const e = loadExpected(key);
      const check = (kind: string, id: string, reason: string, ref?: string): void => {
        if (typeof reason !== "string" || reason.trim().length < 40) {
          problems.push(`${key} ${kind} ${JSON.stringify(id)}: reason must explain the escape (>=40 chars)`);
        }
        if (typeof ref !== "string" || !ref.trim()) {
          problems.push(`${key} ${kind} ${JSON.stringify(id)}: needs a ref (docs/DESIGN-DEVIATIONS.md id, docs/KNOWN_BUGS.md id, or the source of truth)`);
        }
      };
      for (const d of e.dynamic || []) {
        check("dynamic", d.mock, d.reason, d.ref);
        // `match` is the whole point of a dynamic entry — a missing/blanket regex is a silent skip.
        if (typeof d.match !== "string" || !d.match.trim() || /^\^?\.[*+]\$?$/.test(d.match.trim())) {
          problems.push(`${key} dynamic ${JSON.stringify(d.mock)}: "match" must be a real regex, not a blanket wildcard`);
        }
      }
      for (const x of e.extra || []) check("extra", x.text, x.reason, x.ref);
      for (const u of e.undrawn || []) check("undrawn", u.mock, u.reason, u.ref);
    }
    expect(problems).toEqual([]);
  });
});

describe("rendered conformance — mock structure + verbatim copy", () => {
  for (const key of COVERED) {
    it(`${key} renders the mock's copy, in order, with nothing undrawn`, async () => {
      const expected = loadExpected(key);
      const { texts } = await renderWired(key, new Set(expected.texts));
      const result = conformance({
        expected: expected.texts.map((text, i) => ({ text, path: expected.textPaths[i] })),
        actual: texts,
        groups: expected.groups,
        dynamic: expected.dynamic,
        extra: expected.extra,
        undrawn: expected.undrawn,
      });
      if (!result.ok) throw new Error(formatReport(key, result));
      expect(result.ok).toBe(true);
    }, 30000);
  }
});
