# Lynia on Azure: provider pins, backend and provider configuration.
# Plan: docs/plans/2026-09-24-gcp-to-azure-migration.md (D11, H17, X2, S1, S5).
#
# One module, two states. Staging and production are separate state files in the same
# bootstrap-created account (infra/azure/bootstrap.sh), chosen at init time:
#
#   terraform init \
#     -backend-config="storage_account_name=$AZ_TFSTATE_STORAGE_ACCOUNT" \
#     -backend-config="key=staging.tfstate"          # or production.tfstate
#   terraform apply -var environment=staging
#
# Every apply runs in CI (terraform-apply-azure.yml, GitHub environment `infra`), never in
# Cloud Shell: Postgres and Redis creation outlive Cloud Shell's 20-minute idle timeout (X2).

terraform {
  # 1.9.8 is what CI pins (.github/workflows/ci.yml). Nothing here needs newer syntax.
  required_version = ">= 1.9.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.40"
    }
    # azapi only where azurerm has no attribute: ingress session affinity, Easy Auth.
    azapi = {
      source  = "azure/azapi"
      version = "~> 2.0"
    }
    # The scheduler audience app registration (C3 / S2).
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 3.0"
    }
    # Only for the two accepted S1 exceptions: the Postgres admin password. (The Redis key is
    # generated by Azure, not by Terraform, but it is read back into state the same way.)
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }

  # Partial configuration. The static half lives here; the account name and the state key
  # come from -backend-config so one module serves both environments. Entra-only data plane:
  # the state account has shared-key auth disabled (S1), so the backend must use Azure AD.
  # In CI, ARM_USE_OIDC=true + ARM_CLIENT_ID/ARM_TENANT_ID/ARM_SUBSCRIPTION_ID authenticate it.
  backend "azurerm" {
    resource_group_name = "rg-lynia-tfstate"
    container_name      = "tfstate"
    use_azuread_auth    = true
  }
}

provider "azurerm" {
  features {
    key_vault {
      # The vault is bootstrap-owned (keyvault.tf); Terraform must never purge anything in it.
      purge_soft_delete_on_destroy    = false
      recover_soft_deleted_key_vaults = false
    }
    resource_group {
      prevent_deletion_if_contains_resources = true
    }
  }

  # The media account has shared-key auth disabled (D5), so the provider must reach blob
  # data-plane endpoints with Entra tokens instead of account keys.
  storage_use_azuread = true

  # Subscription comes from ARM_SUBSCRIPTION_ID (set from the AZURE_SUBSCRIPTION_ID Variable).
}

provider "azuread" {
  # Tenant comes from ARM_TENANT_ID. The infra identity holds Graph
  # Application.ReadWrite.OwnedBy only (granted by bootstrap.sh); see entra.tf.
}

provider "azapi" {}
