(function(){
const {i,nb,sb,tabs,mark,word,O}=LX;const A='assets/',F='assets/food/';
document.head.insertAdjacentHTML('beforeend',`<style>
.m2h{background:#E9F8EF;padding:0 0 18px}.m2top{position:relative;z-index:1;display:flex;align-items:center;justify-content:space-between;padding:6px 16px 0;gap:12px}
.m2addr{min-width:0;min-height:44px;display:flex;flex-direction:column;justify-content:center}.m2addr small{font:600 11px Inter;color:#5b6670;letter-spacing:.2px}.m2addr span{font:700 15px Inter;display:flex;align-items:center;gap:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.m2greet{position:relative;z-index:1;font:700 24px/1.15 Inter;letter-spacing:-.4px;padding:10px 16px 12px}
.m2tiles{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;padding:16px 16px 0}.m2t{display:flex;flex-direction:column;align-items:center;gap:6px;font:600 12px Inter;letter-spacing:-.2px;position:relative;min-width:0}.m2t div{width:100%;height:76px;border-radius:16px;display:flex;align-items:center;justify-content:center;position:relative}.m2t img{width:54px;height:54px}.m2t span{white-space:nowrap}
.m2send{margin:16px 16px 0;border:1px solid #e2e6ea;border-radius:16px;padding:14px}.m2send b{font:700 16px Inter}.m2send p{margin:2px 0 10px;font-size:13px;color:#5b6670}.m2where{height:48px;border-radius:12px;background:#f6f7f8;display:flex;align-items:center;gap:10px;padding:0 6px 0 14px;font-size:15px;color:#5b6670}.m2where .go{margin-left:auto;width:36px;height:36px;border-radius:50%;background:#00812F;display:flex;align-items:center;justify-content:center}
.m2rh{padding:0 16px;margin:24px 0 10px;display:flex;justify-content:space-between;align-items:flex-end;gap:12px}.m2rh div{min-width:0}.m2rh h3{margin:0;font:700 18px Inter;letter-spacing:-.3px;white-space:nowrap}.m2rh p{margin:2px 0 0;font-size:12.5px;color:#5b6670}.m2rh a{flex:none;font:600 13px Inter;color:#006630;min-height:32px;display:flex;align-items:center}
.m2rail{display:flex;gap:12px;padding:0 16px;overflow:hidden}.m2c{flex:0 0 148px;min-width:0}.m2c .im{height:96px;border-radius:14px;background-size:cover;background-position:center;position:relative;display:flex;align-items:center;justify-content:center}.m2c b{display:block;margin-top:8px;font:700 14px Inter;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.m2c .mt{font-size:12.5px;color:#5b6670;margin-top:2px;display:flex;gap:4px;align-items:center;white-space:nowrap}.m2c .mt i,.m2c .mt svg{flex:none}.m2c .mt svg{color:#C99500;fill:#FFD23F;stroke:#C99500}
.m2free{position:absolute;left:6px;top:6px;background:#4B2FBF;color:#fff;font:700 10.5px Inter;padding:4px 8px;border-radius:999px}.m2eta{position:absolute;right:6px;bottom:6px;background:#fff;color:#14181b;font:700 11px Inter;padding:3px 8px;border-radius:999px}.m2rh h3 img{width:28px;height:28px;vertical-align:-7px;margin-right:6px}.m2kind{position:absolute;left:6px;bottom:6px;background:#fff;font:700 10.5px Inter;padding:3px 8px;border-radius:999px}
.m2live{position:absolute;left:12px;right:12px;bottom:72px;background:#063B22;color:#fff;border-radius:18px;padding:10px 10px 10px 12px;display:flex;align-items:center;gap:10px;z-index:6}.m2live .av{width:40px;height:40px;border-radius:50%;background:#00B14F;display:flex;align-items:center;justify-content:center;flex:none}.m2live b{font:700 14px Inter;display:block}.m2live small{font-size:12px;color:#BFE6CD}.m2live .eta{position:static;background:#FFD23F;color:#3D3100;font:700 13px Inter;padding:6px 10px}.m2live .more{font:700 11px Inter;background:rgba(255,255,255,.14);padding:4px 8px;border-radius:999px;white-space:nowrap}
.m2prog{display:flex;gap:3px;margin-top:6px;width:150px}.m2prog i{flex:1;height:3px;border-radius:2px;background:rgba(255,255,255,.22)}.m2prog i.on{background:#00B14F}
.sk{background:#eef1f3;border-radius:12px}
.dim{position:absolute;inset:0;background:rgba(20,24,27,.45);z-index:7}.sheet{position:absolute;left:0;right:0;bottom:0;background:#fff;border-radius:24px 24px 0 0;z-index:8;padding:8px 16px 24px}.grab{width:36px;height:4px;border-radius:2px;background:#d5dbe0;margin:0 auto 12px}
.srow{display:flex;align-items:center;gap:12px;min-height:56px;border-bottom:1px solid #f0f2f4;font-size:15px}.srow:last-child{border:0}.srow .ic{width:40px;height:40px;border-radius:50%;background:#f6f7f8;display:flex;align-items:center;justify-content:center;flex:none}.srow small{display:block;color:#5b6670;font-size:12.5px}
.hero{margin:0 12px!important;padding-top:12px!important;border-radius:28px}.hero .illus{margin-bottom:20px!important}.meter{display:flex;gap:6px;margin:10px 0 6px}.meter i{flex:1;height:8px;border-radius:4px;background:#00B14F}.meter i.off{background:#CDEEDA}
</style>`);
const st=(w)=>w===320;
const header=(w,o)=>{o=o||{};return `<div class="m2h" style="position:relative;overflow:hidden;border-radius:0 0 28px 28px"><span class="circ" style="width:150px;height:150px;background:#FFD23F;right:-62px;top:-58px;z-index:0"></span><span class="circ" style="width:26px;height:26px;background:#FF6B4A;right:${st(w)?14:78}px;top:${st(w)?100:64}px;z-index:0"></span><span class="circ" style="width:14px;height:14px;background:#3EC1F3;right:${st(w)?50:30}px;top:${st(w)?128:112}px;z-index:0"></span>${sb()}<div class="m2top"><div class="m2addr"><small>${o.noloc?'NO ADDRESS YET':'DELIVERING TO'}</small><span style="color:${o.noloc?'#8F2418':'#14181b'}">${i('map-pin',16,o.noloc?'#C0392B':'#00B14F')}${o.noloc?'Set your location':'12 Samora Machel Ave'}${i('chevron-down',16)}</span></div><div class="bell">${i('bell',20,'#006630')}</div></div><div class="m2greet">${st(w)?'Good evening,<br><span style="color:#006630">Tatendashe</span>':'Good morning, <span style="color:#006630">Rudo</span>'}</div><div style="padding:0 16px;position:relative;z-index:1"><div class="search" style="border:0">${i('search',18)}${st(w)?'Search food or shops':'Search food, shops or parcels'}</div></div></div>`};
const T4=[['send','Send','#CDEEDA'],['restaurants','Restaurants','#FFD9CC'],['shops','Shops','#DDD5FF'],['pharmacy','Pharmacy','#C5E9DF']];
const tiles=(w)=>`<div class="m2tiles">${T4.map(t=>`<div class="m2t"><div style="background:${t[2]}${st(w)?';height:64px':''}"><img src="${A}service-icons/v2/${t[0]}.svg" style="${st(w)?'width:44px;height:44px':''}"></div><span style="${st(w)?'font-size:11px':''}">${st(w)&&t[0]==='restaurants'?'Food':t[1]}</span></div>`).join('')}</div>`;
const send=()=>`<div class="m2send"><b>Send a parcel</b><p>Name your price. Nearby riders make offers.</p><div class="m2where">${i('package',18,'#006630')}Where is it going?<span class="go">${i('arrow-right',18,'#fff')}</span></div></div>`;
const R=[['Golden Bao','biryani',4.9,25,0],['Mbuya\u2019s Kitchen','rice',4.8,25,1.5],['Fresh Press','dosa',4.5,30,0],['Harare Grill Co.','burger',4.6,30,2]];
const SH=[['Avondale Pharmacy','Pharmacy','#DFF4EE','#006630',0],['Mbare Fresh','Grocery','#E9F8EF','#006630',0],['Borrowdale Butchery','Butchery','#FFE7E0','#8F2418',1.5],['Sam Levy Threads','Fashion','#FFE4F2','#8A1F5C',2]];
const tag=(e,f)=>`<span class="m2eta tnum">${e} min</span>${f?'':'<span class="m2free">Free delivery</span>'}`;const meta=(r,e,f)=>`<div class="mt tnum">${i('star',12,'#C99500')}<span style="color:#14181b;font-weight:600">${r}</span>${f?'·<span>$'+f.toFixed(2)+' delivery</span>':''}</div>`;
const rc=(r)=>`<div class="m2c"><div class="im" style="background-image:url(${F}${r[1]}-1.jpg)">${tag(r[3],r[4])}</div><b>${r[0]}</b>${meta(r[2],r[3],r[4])}</div>`;
const sc=(s)=>`<div class="m2c"><div class="im" style="background:${s[2]}"><span style="font:700 36px Inter;color:${s[3]}">${s[0][0]}</span><span class="m2kind" style="color:${s[3]}">${s[1]}</span>${tag(35,s[4])}</div><b>${s[0]}</b>${meta(4.7,35,s[4])}</div>`;
const rail=(t,sub,cards,n,ic)=>`<div class="m2rh"><div><h3>${ic?`<img src="${A}service-icons/v2/${ic}.svg">`:''}${t}</h3>${sub?`<p>${sub}</p>`:''}</div><a>See all</a></div><div class="m2rail">${cards}</div>${n?`<div style="padding:6px 16px 0">${nb(n)}</div>`:''}`;
const rails=()=>rail('Popular restaurants','Most ordered near you',R.map(rc).join(''),'popularity ranking','restaurants')+rail('Popular shops','Pharmacy, grocery, butchery and more',SH.map(sc).join(''),'','shops');
const live=()=>`<div class="m2live"><span class="av">${i('bike',20,'#fff')}</span><div style="flex:1;min-width:0"><b>Tendai is on the way</b><small>Parcel to Avondale · <span class="more">+1 order</span></small><div class="m2prog">${[1,1,1,1,1,0,0].map(x=>`<i class="${x?'on':''}"></i>`).join('')}</div></div><span class="eta tnum">12 min</span></div>`;
const skRail=()=>`<div class="m2rh"><div class="sk" style="width:150px;height:18px"></div></div><div class="m2rail">${[0,1,2].map(()=>`<div class="m2c"><div class="sk" style="height:96px;border-radius:14px"></div><div class="sk" style="height:12px;width:110px;margin-top:10px"></div><div class="sk" style="height:10px;width:70px;margin-top:6px"></div></div>`).join('')}</div>`;
const H={
home:(w)=>`${header(w)}${tiles(w)}${rails()}<div style="height:24px"></div>${tabs()}`,
fold:(w)=>`<div style="height:${st(w)?640:720}px;overflow:hidden;position:relative">${header(w)}${tiles(w)}${rails()}<div style="position:absolute;left:0;right:0;bottom:0">${tabs()}</div>${live()}</div>`,
skel:()=>`<div style="height:720px;overflow:hidden;position:relative">${header(360)}${tiles(360)}${skRail()}${skRail()}<div style="position:absolute;left:0;right:0;bottom:0">${tabs()}</div></div>`,
noloc:()=>`<div style="height:720px;overflow:hidden;position:relative">${header(360,{noloc:1})}${tiles(360)}<div style="margin:24px 16px 0;background:#E9F8EF;border-radius:20px;padding:20px;text-align:center"><img src="${A}illustrations/trust-tracking.svg" style="height:110px"><div style="font:700 18px Inter;margin-top:8px">Where should we deliver?</div><p class="sub" style="font-size:14px;margin:6px 0 16px">Set your area to see restaurants and shops that deliver to you.</p><div class="btn" style="background:#00812F;color:#fff">${i('navigation',18,'#fff')}Use my location</div><div class="btn" style="height:48px;color:#006630;margin-top:8px">Type an address</div></div><div style="position:absolute;left:0;right:0;bottom:0">${tabs()}</div></div>`,
locsheet:()=>`<div style="height:720px;overflow:hidden;position:relative">${header(360)}${tiles(360)}<div class="dim"></div><div class="sheet"><div class="grab"></div><div style="font:700 20px Inter;margin-bottom:12px">Deliver to</div><div class="search" style="background:#f6f7f8;border:0">${i('search',18)}Search street, suburb or landmark</div><div style="margin-top:8px"><div class="srow"><span class="ic" style="background:#E9F8EF">${i('navigation',18,'#006630')}</span><div><b style="color:#006630">Use my current location</b><small>Most accurate for your rider</small></div></div><div class="srow"><span class="ic">${i('store',18)}</span><div><b>Home</b><small>12 Samora Machel Ave, CBD</small></div>${i('check',18,'#00B14F')}</div><div class="srow"><span class="ic">${i('package',18)}</span><div><b>Work</b><small>Eastgate Mall, 3rd floor</small></div></div><div class="srow"><span class="ic">${i('plus',18)}</span><b>Add a place</b></div></div></div></div>`,
notify:()=>`<div style="height:720px;overflow:hidden;position:relative">${header(360)}${tiles(360)}<div class="dim"></div><div class="sheet" style="text-align:center"><div class="grab"></div><div style="width:96px;height:96px;margin:8px auto 0;background:#ECE8FF;border-radius:28px;display:flex;align-items:center;justify-content:center"><img src="${A}service-icons/v2/shops.svg" style="width:64px"></div><div style="font:700 22px Inter;margin-top:16px;letter-spacing:-.3px">Shops are coming soon</div><p class="sub" style="font-size:14.5px;margin:8px 0 20px">Groceries, butcheries, fashion and auto parts from shops near you. We\u2019ll message you on WhatsApp the day they open in your area.</p><div class="btn" style="background:#00812F;color:#fff">Notify me</div><div class="btn" style="height:48px;color:#006630;margin-top:8px">Not now</div><div style="margin-top:8px">${nb('notify-me list')}</div></div></div>`
};
const OB={
otp:(T)=>O.otp(T).replace(/<div class="foot">[\s\S]*$/,'<div class="foot"><div class="link" style="font-weight:600">Fills in by itself when the message arrives. We check it automatically.</div></div>'),
verified:()=>`${sb()}<div class="pad"><div style="background:#E9F8EF;border-radius:20px;padding:18px;text-align:center;margin-top:8px"><img src="${A}illustrations/trust-verified.svg" style="height:120px"><div style="font:700 24px Inter;letter-spacing:-.4px;margin-top:6px">You\u2019re verified, Tendai</div><p class="sub" style="margin:6px 0 0;font-size:14px">You can go online and take jobs now.</p></div><div style="border:1px solid #e2e6ea;border-radius:16px;padding:14px;margin-top:14px"><div style="display:flex;justify-content:space-between;font-size:14px"><b>Commission-free jobs</b><b class="tnum" style="color:#006630">5 of 5 left</b></div><div class="meter">${[1,1,1,1,1].map(()=>'<i></i>').join('')}</div><p style="margin:0;font-size:12.5px;color:#5b6670;line-height:1.45">After these, commission comes off a prepaid balance. We\u2019ll remind you before you need to top up. ${nb('free-jobs rule')}</p></div></div><div class="foot">${LX.cta({cta:'#00812F',ctaInk:'#fff'},`${i('power',18,'#fff')}Go online`)}<div class="link" style="font-size:13px">Add licence and bike papers later in Account</div></div>`,
account:()=>`${sb()}<div class="pad"><h2>Account</h2><div style="display:flex;gap:12px;align-items:center;padding:8px 0 16px"><span style="width:52px;height:52px;border-radius:50%;background:#E9F8EF;display:flex;align-items:center;justify-content:center;font:700 20px Inter;color:#006630">C</span><div><b style="font-size:16px">Chipo Marufu</b><div class="muted tnum" style="font-size:13px">+263 77 245 1180</div></div></div><div style="background:#ECE8FF;border-radius:20px;padding:16px;display:flex;gap:12px;align-items:center"><div style="flex:1"><b style="font-size:16px;color:#14181b">Ride with LyniaGo</b><p style="margin:4px 0 12px;font-size:13px;color:#3B23A0;line-height:1.4">Set your fare, get paid in cash. All you need is your national ID.</p><span class="btn" style="height:44px;background:#14181B;color:#fff;display:inline-flex;padding:0 18px;font-size:14px">Start in 3 minutes</span></div><img src="${A}illustrations/biz-scooter-rider.svg" style="width:96px"></div><div style="margin-top:12px">${['Personal details|Name, phone, optional ID','Saved places|Home, Work','Payments|Cash, EcoCash, InnBucks','Help'].map(s=>{const[a,b]=s.split('|');return `<div class="srow"><div style="flex:1"><b style="font-weight:600">${a}</b>${b?`<small>${b}</small>`:''}</div>${i('chevron-right',18,'#5b6670')}</div>`}).join('')}</div></div><div style="position:absolute;left:0;right:0;bottom:0"><div class="tabbar"><div class="tab">${i('store',22)}<span>Home</span></div><div class="tab">${i('receipt',22)}<span>Orders</span></div><div class="tab on">${i('user',22)}<span>Account</span></div></div></div>`
};
window.M2={H,OB};
})();
