(function(){
const A='assets/',F='assets/food/';
const i=(n,s,c)=>`<i data-lucide="${n}" style="width:${s||18}px;height:${s||18}px;color:${c||'currentColor'};display:inline-flex"></i>`;
const nb=(t)=>`<span class="nb">NEEDS BACKEND${t?' · '+t:''}</span>`;
const sb=(dark)=>`<div class="sb" style="color:${dark?'#fff':'#14181b'}"><span class="tnum">9:41</span><span class="tnum">3G 84%</span></div>`;
const tabs=()=>`<div class="tabbar"><div class="tab on">${i('store',22)}<span>Home</span></div><div class="tab">${i('receipt',22)}<span>Orders</span></div><div class="tab">${i('user',22)}<span>Account</span></div></div>`;
const R=[['Golden Bao','biryani',4.9,25,0],['Mbuya\u2019s Kitchen','rice',4.8,25,1.5],['Fresh Press','dosa',4.5,30,0],['Harare Grill Co.','burger',4.6,30,2]];
const SH=[['Avondale Pharmacy','Pharmacy','#DFF4EE','#006630',0],['Mbare Fresh','Grocery','#E9F8EF','#006630',1.5],['Borrowdale Butchery','Butchery','#FFE7E0','#8F2418',0],['Sam Levy Threads','Fashion','#FFE4F2','#8A1F5C',2],['Msasa Auto Spares','Auto parts','#E3F6FE','#0B5A7A',1.5]];
const fee=(f)=>f?`<span class="tnum muted">$${f.toFixed(2)} delivery</span>`:`<span class="free">Free delivery</span>`;
function vcard(r,shadow){return `<div class="vc" style="${shadow?'border:0;box-shadow:0 2px 10px rgba(6,59,34,.10)':''}"><div class="img" style="background-image:url(${F}${r[1]}-1.jpg)"><span class="eta tnum">${r[3]} min</span></div><div class="vb"><b>${r[0]}</b><div class="row"><span class="tnum">${i('star',12,'#C99500')} ${r[2]}</span></div>${fee(r[4])}</div></div>`}
function scard(s,shadow){return `<div class="vc" style="${shadow?'border:0;box-shadow:0 2px 10px rgba(6,59,34,.10)':''}"><div class="img" style="background:${s[2]};display:flex;align-items:center;justify-content:center"><span style="font:700 34px Inter;color:${s[3]}">${s[0][0]}</span><span class="kind" style="color:${s[3]}">${s[1]}</span><span class="eta tnum">35 min</span></div><div class="vb"><b>${s[0]}</b><div class="row"><span class="tnum">${i('star',12,'#C99500')} 4.7</span></div>${fee(s[4])}</div></div>`}
function rail(title,kind,filter,o){o=o||{};let list=kind==='r'?R:SH;if(filter==='free')list=list.filter(x=>!x[4]).concat(list.filter(x=>!x[4]));
const cards=list.slice(0,4).map(x=>kind==='r'?vcard(x,o.shadow):scard(x,o.shadow)).join('');
return `<section style="${o.band?`background:${o.band};padding:18px 0 20px;margin-top:16px;`:''}"><div class="rail-h"><h3>${o.dot?`<span class="dot" style="background:${o.dot};margin-right:6px"></span>`:''}${title}</h3><a>See all ${i('arrow-right',14)}</a></div><div class="rail">${cards}</div>${o.nb?`<div style="padding:6px 16px 0">${nb(o.nb)}</div>`:''}</section>`}
const rails=(o)=>rail('Restaurants with free delivery','r','free',Object.assign({nb:'merchant free-delivery flag'},o&&o.r1))+rail('Popular restaurants','r','pop',Object.assign({nb:'popularity ranking'},o&&o.r2))+rail('Shops with free delivery','s','free',Object.assign({nb:'customer shop list'},o&&o.s1))+rail('Popular shops','s','pop',o&&o.s2);
const T4=[['send','Send','#E9F8EF'],['restaurants','Restaurants','#FFE7E0'],['shops','Shops','#ECE8FF',1],['pharmacy','Pharmacy','#DFF4EE',1]];
function tiles(style){return `<div class="tiles">${T4.map(t=>{const img=`<img src="${A}service-icons/v2/${t[0]}.svg" alt="">`,soon=t[3]?'<span class="soon">SOON</span>':'';
if(style==='round')return `<div class="tile round"><div class="blob" style="background:${t[2]}">${img}${soon}</div><span>${t[1]}</span></div>`;
if(style==='white')return `<div class="tile" style="background:#fff;box-shadow:0 2px 10px rgba(6,59,34,.12)">${img}<span>${t[1]}</span>${soon}</div>`;
return `<div class="tile" style="background:${t[2]}">${img}<span>${t[1]}</span>${soon}</div>`}).join('')}</div>`}
function tracker(o){o=o||{};const bar=(n)=>`<div class="seg">${[0,1,2,3,4,5,6].map(k=>`<i style="background:${k<n?'#00B14F':'#CDEEDA'}"></i>`).join('')}</div>`;
const row=(ic,t,s,n,eta)=>`<div class="trow"><span class="tic">${i(ic,18,'#fff')}</span><div style="flex:1;min-width:0"><b>${t}</b><div class="muted" style="font-size:12px">${s}</div>${bar(n)}</div><span class="etac tnum">${eta}</span></div>`;
return `<div class="tracker" style="${o.shadow?'border:0;box-shadow:0 2px 10px rgba(6,59,34,.10)':''}${o.bg?';background:'+o.bg:''}">${row('package','Parcel to Avondale','Tendai M. · on the way to drop-off',5,'12 min')}<div class="hr"></div>${row('utensils','Golden Bao','Preparing · finding a rider',2,'25 min')}</div>`}
function cta(T,label,o){o=o||{};return `<div class="btn" style="background:${o.bg||T.cta};color:${o.ink||T.ctaInk}">${label}</div>`}
const ghost=(label,c)=>`<div class="btn" style="background:transparent;border:1px solid #e2e6ea;color:${c||'#006630'};height:48px">${label}</div>`;
const mark=(w)=>`<img src="${A}brand/lyniago-mark.svg" style="width:${w||28}px;height:auto">`;
const word=(c,s)=>`<span style="font:600 ${s||20}px Fredoka,Inter;color:${c||'#14181b'};letter-spacing:-.2px">Lynia<span style="color:${c==='#fff'?'#fff':'#00B14F'}">Go</span></span>`;
function hero(T,img,h){return `<div class="hero" style="background:${T.heroBg};height:${h||270}px">${T.circles?`<span class="circ" style="width:120px;height:120px;background:#FFD23F;right:-30px;top:40px"></span><span class="circ" style="width:44px;height:44px;background:#FF6B4A;left:22px;top:44px"></span>`:''}<div class="illus" style="${T.tilt?'transform:rotate(-3deg);background:#fff;border-radius:22px;padding:10px;box-shadow:0 8px 24px rgba(0,0,0,.18)':''}"><img src="${A}illustrations/${img}.svg"></div></div>`}
const O={
welcome:(T)=>`${sb(T.heroDark)}<div style="position:absolute;inset:0;z-index:-1"></div>${hero(T,'hero-rider',300)}<div class="pad" style="padding-top:20px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:12px">${mark(24)}${word()}</div><h1>Parcels and food<br><span style="color:${T.h1Accent}">across town.</span></h1><div class="facts"><div>${i('banknote',18,'#006630')}Cash or mobile money</div><div>${i('circle-check',18,'#006630')}A code at the door, every delivery</div><div>${i('timer',18,'#006630')}Live tracking to your gate</div></div></div><div class="foot">${cta(T,'Continue with your number')}<div class="link">Want to earn? <b>Ride with LyniaGo ${i('arrow-right',14)}</b></div></div>`,
phone:(T,st)=>`${sb()}<div class="pad"><div class="back">${i('chevron-right',22)}</div><h2>What\u2019s your number?</h2><p class="sub">We\u2019ll send a 6-digit code on WhatsApp.</p><label>Phone number</label><div class="field ${st==='err'?'err':''}"><span class="pre">+263</span><span class="tnum">${st==='err'?'77 245 118':'77 245 1180'}</span></div>${st==='err'?'<div class="errt">That number looks short. Zimbabwe mobiles have 9 digits after +263.</div>':'<div class="help">Starts with 71, 73, 77 or 78.</div>'}</div><div class="foot">${cta(T,'Send code')}<div class="link small">By continuing you agree to the <b>Terms</b> and <b>Privacy policy</b>.</div></div>`,
otp:(T)=>`${sb()}<div class="pad"><div class="back">${i('chevron-right',22)}</div><h2>Enter the code</h2><p class="sub">Sent on <b style="color:#14181b">WhatsApp</b> to <span class="tnum">+263 77 245 1180</span>. <b style="color:#006630">Change</b></p><div class="otp tnum"><span>4</span><span>1</span><span>8</span><span>2</span><span class="cur"></span><span></span></div><div class="help" style="display:flex;gap:6px;align-items:center;margin-top:14px">${i('clock',16)} <span class="tnum">Resend in 0:42</span></div><div class="link" style="justify-content:flex-start;margin-top:16px;color:#9aa3ab">${i('refresh-cw',16,'#9aa3ab')}<span>Resend on WhatsApp</span></div></div><div class="foot">${cta(T,'Verify')}</div>`,
name:(T)=>`${sb()}<div class="pad"><h2>What should riders call you?</h2><p class="sub">Your name shows on your rider\u2019s screen and your receipts.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><div><label>First name</label><div class="field"><span>Chipo</span></div></div><div><label>Surname</label><div class="field"><span>Marufu</span></div></div></div><div class="vrow">${i('circle-check',18,'#00B14F')}<span class="tnum">+263 77 245 1180</span><b>Verified</b></div><div class="note">${i('id-card',18,'#5b6670')}<span>No ID needed. If an order ever needs one, we\u2019ll ask then. You can add it in Account.</span></div></div><div class="foot">${cta(T,'Start using LyniaGo')}</div>`,
rider:(T)=>`${sb(T.riderDark)}<div class="hero" style="background:${T.riderBg};height:210px">${T.circles?`<span class="circ" style="width:90px;height:90px;background:#3EC1F3;right:-20px;top:20px"></span>`:''}<div class="illus" style="height:170px"><img src="${A}illustrations/biz-scooter-rider.svg" style="height:170px"></div></div><div class="pad" style="padding-top:16px"><h1 style="font-size:24px">Ride with LyniaGo.<br><span style="color:${T.riderAccent}">Earn on your terms.</span></h1><div class="chips"><span>You set your fare</span><span>Cash on delivery</span><span>Ride when you want</span></div><div class="steps"><div class="st done">${i('check',14,'#fff')}<b>Your account</b><em>Done</em></div><div class="st"><span>2</span><b>ID check with Didit</b><em class="tnum">~2 min</em></div><div class="st"><span>3</span><b>Rider photo for your profile</b><em class="tnum">~30 sec</em></div></div><div class="note" style="margin-top:10px">${i('wallet',18,'#5b6670')}<span>No top-up to start. Your first jobs are commission-free. Licence and bike papers can wait. ${nb('free-jobs rule')}</span></div></div><div class="foot" style="bottom:16px">${cta(T,'Start ID check')}</div>`,
pending:(T)=>`${sb()}<div class="pad"><div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">Rider setup</h2><span class="pill">${i('clock',14)} Checking</span></div><div class="pend"><img src="assets/illustrations/trust-verified.svg"><div><b>Didit is checking your ID</b><p class="sub" style="margin:4px 0 0">Usually under a minute. We\u2019ll notify you, so you can leave this screen.</p></div></div><div class="steps"><div class="st done">${i('check',14,'#fff')}<b>Your account</b><em>Done</em></div><div class="st done">${i('check',14,'#fff')}<b>Rider photo</b><em>Done</em></div><div class="st now"><span class="spin"></span><b>ID check</b><em>In review</em></div><div class="st"><span>4</span><b>Go online</b><em>Next</em></div></div><p class="sub" style="font-size:13px">If something needs fixing, we\u2019ll tell you exactly what. Nothing is lost if you close the app.</p></div><div class="foot">${ghost('Send a parcel while you wait')}</div>`
};
window.LX={i,nb,sb,tabs,tiles,tracker,rails,rail,cta,ghost,mark,word,O};
})();
